# Free Steak Dinner VOR Model — 2026

Rebuilt from the 2025 notebook with these changes:

1. **Scoring uses actual Yahoo league settings** — half-PPR (0.5/rec), 6-pt passing TDs, −1 INT, rushing first downs
   now actually scored at 0.5 (was computed but commented out).
2. **Replacement levels computed programmatically every run** from roster
   structure (12 teams, 1QB/2RB/3WR/1TE + flex) — replaces the hardcoded
   `replacement_values = {...}` that went stale whenever FantasyPros updated.
3. **Consistent baseline** — replacement level is taken from the same
   points column that player VOR is computed from (the 2025 model
   subtracted unadjusted replacement values from adjusted player points).
4. **Header-name-based scraping** — columns are matched by their header text
   (including the PASSING/RUSHING/RECEIVING group row), so if FantasyPros
   reorders columns you get a loud error instead of silently wrong stats.
5. **Merge safety** — names are normalized (suffixes, punctuation, team
   aliases) before joining projections to ADP, and unmatched players are
   PRINTED instead of silently dropped.
6. **Half-PPR ADP page** (was scraping the full-PPR page) and a
   **VALUE = ADP rank − VOR rank** column: positive = the room will likely
   let this player fall past his real value in THIS league's scoring.
7. **K + DST included** (your league starts both) with approximated scoring.
8. **Gap-based tiers** per position, and **dated CSV snapshots** of every
   scrape so you can reproduce any board later (and backtest).

In [1]:
# ============================================================
# CELL 1 — LEAGUE CONFIG  (complete, self-contained)
# Free Steak Dinner NFL — Yahoo league 410984
# 12 teams · half-PPR · 6-pt pass TD · 0.5 rushing 1D
# ============================================================
import json
import re
from datetime import date

import pandas as pd
import requests
from bs4 import BeautifulSoup

# Used by the FantasyPros ECR overlay in Cell 3.
HEADERS = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}

POSITIONS = ["QB", "RB", "WR", "TE", "K", "DST"]

# --- Scoring -------------------------------------------------------------
# NOT modeled (each needs TD-level or play-level detail no projection
# source breaks out): 40+ yard TD bonuses, return TDs, offensive fumble
# return TDs, the extra -2 pick-six penalty, missed FG 0-19.
SCORING = {
    # passing
    "pass_yd": 0.04,       # 25 passing yards per point
    "pass_td": 6.0,        # league override (Yahoo default is 4)
    "int": -1.0,           # league value (2025 model wrongly used -2)
    "pass_40p": 1.0,       # 40+ yard completions
    # rushing
    "rush_yd": 0.1,        # 10 rushing yards per point
    "rush_td": 6.0,
    "rush_fd": 0.5,        # rushing 1st downs — now a REAL projected stat
    "rush_1d": 0.5,        # alias, kept so an un-replaced Cell 4 still runs
    "rush_40p": 2.0,       # 40+ yard runs
    # receiving
    "rec": 0.5,            # HALF-PPR (2025 model wrongly used full PPR)
    "rec_yd": 0.1,
    "rec_td": 6.0,
    "rec_40p": 1.0,        # 40+ yard receptions
    # misc
    "fumble": -2.0,
    "two_pt": 2.0,         # applies to pass/rush/rec conversions alike
    # kicker — exact distance tiers used when the source provides buckets,
    # otherwise fg_avg is the fallback approximation
    "fg_0_19": 3.0, "fg_20_29": 3.0, "fg_30_39": 3.0,
    "fg_40_49": 4.0, "fg_50p": 5.0,
    "fg_avg": 3.6,
    "xp": 1.0,
    # team defense
    "dst_sack": 1.0, "dst_int": 2.0, "dst_fr": 2.0,
    "dst_td": 6.0, "dst_safety": 2.0,
}

# Fallback only. Sleeper projects rush_fd directly, so these rates are used
# just in case that field is ever missing for a player.
RUSH_1D_RATES = {"QB": 0.08, "RB": 0.05, "WR": 0.05, "TE": 0.05, "K": 0.0, "DST": 0.0}

# --- Roster (drives replacement levels) ----------------------------------
ROSTER = {
    "teams": 12,
    "slots": {"QB": 1, "RB": 2, "WR": 3, "TE": 1, "K": 1, "DST": 1},
    "flex": 1,                                    # the W/R/T spot
    "flex_split": {"RB": 0.75, "WR": 0.25, "TE": 0.0},
}
# e.g. {"QB": 15} to model streaming; your league has no waiver priority
# and unlimited adds, so effective QB/TE/DST replacement runs a bit higher.
REPLACEMENT_OVERRIDE = {}

In [2]:
# ============================================================
# CELL 2 (REPLACEMENT) — SLEEPER PROJECTIONS API
#
# Why the rewrite: FantasyPros moved projections + ADP to client-side
# rendering in 2026. Their HTML now serves only 10 rows per position and
# the ADP table is gone entirely. Sleeper's public projections endpoint
# returns full-season stat lines AND half-PPR ADP as JSON — no auth, no
# HTML parsing, and no cross-source name matching (stats and ADP arrive
# in the same record).
#
# Bonus: Sleeper projects rush_fd (rushing first downs) directly, so the
# RUSH_1D_RATES estimate is no longer needed. It also gives rec_40p for
# your league's 40+ yard reception bonus, and gp (games played).
# ============================================================
SLEEPER_SEASON = "2026"
SLEEPER_URL = f"https://api.sleeper.app/projections/nfl/{SLEEPER_SEASON}"

# canonical column -> Sleeper stat key. Missing keys resolve to 0.0 and are
# listed in the discovery report, so a renamed field is visible, never silent.
STAT_MAP = {
    "PASS_YD": "pass_yd", "PASS_TD": "pass_td", "INT": "pass_int",
    "PASS_40P": "pass_40p", "PASS_2PT": "pass_2pt",
    "RUSH_ATT": "rush_att", "RUSH_YD": "rush_yd", "RUSH_TD": "rush_td",
    "RUSH_FD": "rush_fd", "RUSH_40P": "rush_40p", "RUSH_2PT": "rush_2pt",
    "REC": "rec", "REC_YD": "rec_yd", "REC_TD": "rec_td",
    "REC_FD": "rec_fd", "REC_40P": "rec_40p", "REC_2PT": "rec_2pt",
    "FL": "fum_lost", "GP": "gp",
    # kicker
    "FG": "fgm", "XPT": "xpm",
    "FG_0_19": "fgm_0_19", "FG_20_29": "fgm_20_29", "FG_30_39": "fgm_30_39",
    "FG_40_49": "fgm_40_49", "FG_50P": "fgm_50p",
    # team defense
    "DST_SACK": "sack", "DST_INT": "int", "DST_FR": "fum_rec",
    "DST_TD": "def_td", "DST_SAFETY": "safe", "DST_PA": "pts_allow",
    # source ADP + Sleeper's own scoring (reference only)
    "ADP_HALF": "adp_half_ppr", "SLEEPER_PTS_HALF": "pts_half_ppr",
}

ALL_STAT_COLS = list(STAT_MAP.keys())
SLEEPER_POS_MAP = {"DEF": "DST"}   # Sleeper calls team defense DEF
ADP_UNDRAFTED = 900.0              # Sleeper uses 999.0 as "no ADP" sentinel

def fetch_sleeper():
    """One call returns every projected player. We filter by position
    client-side rather than trusting the position[] query param."""
    params = [("season_type", "regular"), ("order_by", "adp_half_ppr")]
    for p in ("QB", "RB", "WR", "TE", "K", "DEF"):
        params.append(("position[]", p))
    r = requests.get(SLEEPER_URL, params=params, timeout=60)
    r.raise_for_status()
    data = r.json()
    if not isinstance(data, list) or not data:
        raise RuntimeError(f"Sleeper returned unexpected payload: {type(data)}")
    return data

def sleeper_to_frame(records):
    """Flatten Sleeper records into the canonical schema the rest of this
    notebook already uses (Player / Team / POS / stat columns)."""
    rows, seen_keys = [], {}
    for rec in records:
        p = rec.get("player") or {}
        stats = rec.get("stats") or {}
        pos = p.get("position") or (p.get("fantasy_positions") or [None])[0]
        if not pos:
            continue
        pos = SLEEPER_POS_MAP.get(pos, pos)
        if pos not in POSITIONS:
            continue

        name = (p.get("full_name")
                or " ".join(filter(None, [p.get("first_name"), p.get("last_name")]))
                or p.get("last_name") or "").strip()
        if not name:
            continue

        row = {"Player": name,
               "Team": (p.get("team") or "FA"),
               "POS": pos,
               "SLEEPER_ID": rec.get("player_id") or p.get("player_id")}
        for col, key in STAT_MAP.items():
            row[col] = float(stats.get(key) or 0.0)
        rows.append(row)
        seen_keys.setdefault(pos, set()).update(stats.keys())

    df = pd.DataFrame(rows)
    # ADP: 999.0 means undrafted -> treat as missing
    df.loc[df["ADP_HALF"] >= ADP_UNDRAFTED, "ADP_HALF"] = float("nan")
    df.loc[df["ADP_HALF"] == 0.0, "ADP_HALF"] = float("nan")
    return df, seen_keys

def discovery_report(df, seen_keys):
    """Prints which mapped fields actually came back, and what else is
    available. Read this once after a season rollover or API change."""
    print("\n--- DISCOVERY REPORT ---")
    mapped = set(STAT_MAP.values())
    for pos in POSITIONS:
        keys = seen_keys.get(pos, set())
        if not keys:
            print(f"{pos}: NO RECORDS")
            continue
        missing = sorted(k for k in mapped if k not in keys)
        print(f"{pos}: {len(df[df['POS'] == pos])} players, {len(keys)} stat keys")
        if missing:
            print(f"   mapped-but-absent: {missing}")
    all_keys = sorted(set().union(*seen_keys.values())) if seen_keys else []
    unused = [k for k in all_keys if k not in mapped]
    print(f"\nAvailable but unused ({len(unused)}): {unused}")

In [3]:
# ============================================================
# CELL 3 (REPLACEMENT) — FETCH + SNAPSHOT
# Optionally overlays FantasyPros ECR/tier from the cheatsheets
# page, which still works (it's the only FP endpoint that does).
# ============================================================
USE_FANTASYPROS_ECR = True   # set False to run purely on Sleeper

records = fetch_sleeper()
print(f"Sleeper: {len(records)} raw records")
proj, seen_keys = sleeper_to_frame(records)
print(f"usable players: {len(proj)}")
discovery_report(proj, seen_keys)

# --- ADP straight from the same payload (no name matching needed) ---
adp = (proj.loc[proj["ADP_HALF"].notna(), ["Player", "Team", "POS", "ADP_HALF"]]
       .sort_values("ADP_HALF").reset_index(drop=True))
adp["ADP_RANK"] = adp.index + 1
adp = adp.rename(columns={"ADP_HALF": "AVG"})
adp["Bye"] = None
print(f"\nplayers with half-PPR ADP: {len(adp)}")

# --- optional FantasyPros ECR overlay (cheatsheets ecrData still works) ---
if USE_FANTASYPROS_ECR:
    def extract_js_json(html, varname):
        i = html.find(varname)
        if i == -1:
            raise ValueError(f"{varname} not found")
        s = html.find("=", i) + 1
        while html[s] in " \t\r\n":
            s += 1
        oc = html[s]; cc = "}" if oc == "{" else "]"
        depth = 0; j = s; in_str = False; esc = False
        while j < len(html):
            c = html[j]
            if in_str:
                if esc: esc = False
                elif c == "\\": esc = True
                elif c == '"': in_str = False
            else:
                if c == '"': in_str = True
                elif c == oc: depth += 1
                elif c == cc:
                    depth -= 1
                    if depth == 0:
                        return json.loads(html[s:j + 1])
            j += 1
        raise ValueError(f"unterminated {varname}")

    fp_html = requests.get(
        "https://www.fantasypros.com/nfl/rankings/half-point-ppr-cheatsheets.php",
        headers=HEADERS, timeout=30).text
    ecr = extract_js_json(fp_html, "ecrData")
    fp = pd.DataFrame([{
        "Player": p["player_name"],
        "POS": SLEEPER_POS_MAP.get(p["player_position_id"], p["player_position_id"]),
        "ECR": p.get("rank_ecr"),
        "FP_TIER": p.get("tier"),
        "Bye": p.get("player_bye_week"),
    } for p in ecr["players"]])
    print(f"FantasyPros ECR: {len(fp)} players (as of {ecr.get('last_updated')})")
else:
    fp = None

stamp = date.today().isoformat()
proj.to_csv(f"projections_{stamp}.csv", index=False)
adp.to_csv(f"adp_{stamp}.csv", index=False)
print(f"snapshots saved: projections_{stamp}.csv, adp_{stamp}.csv")

# Only players with real rushing volume tell us whether the field is populated.
_r = proj[(proj["POS"].isin(["QB", "RB"])) & (proj["RUSH_ATT"] >= 20)]
share = (_r["RUSH_FD"] > 0).mean()
RUSH_FD_OK = bool(share > 0.8)
print(f"rush_fd populated for {share:.0%} of {len(_r)} QB/RB with 20+ carries "
      f"-> RUSH_FD_OK={RUSH_FD_OK}")

Sleeper: 3301 raw records
usable players: 3226

--- DISCOVERY REPORT ---
QB: 355 players, 31 stat keys
   mapped-but-absent: ['def_td', 'fgm', 'fgm_0_19', 'fgm_20_29', 'fgm_30_39', 'fgm_40_49', 'fgm_50p', 'fum_rec', 'int', 'pass_40p', 'pts_allow', 'rec', 'rec_2pt', 'rec_40p', 'rec_fd', 'rec_td', 'rec_yd', 'rush_40p', 'sack', 'safe', 'xpm']
RB: 677 players, 35 stat keys
   mapped-but-absent: ['def_td', 'fgm', 'fgm_0_19', 'fgm_20_29', 'fgm_30_39', 'fgm_40_49', 'fgm_50p', 'fum_rec', 'int', 'pass_2pt', 'pass_40p', 'pass_int', 'pass_td', 'pass_yd', 'pts_allow', 'rec_2pt', 'rush_40p', 'sack', 'safe', 'xpm']
WR: 1365 players, 40 stat keys
   mapped-but-absent: ['def_td', 'fgm', 'fgm_0_19', 'fgm_20_29', 'fgm_30_39', 'fgm_40_49', 'fgm_50p', 'fum_rec', 'int', 'pass_2pt', 'pass_40p', 'pass_int', 'pass_td', 'pass_yd', 'pts_allow', 'rush_2pt', 'rush_40p', 'sack', 'safe', 'xpm']
TE: 644 players, 34 stat keys
   mapped-but-absent: ['def_td', 'fgm', 'fgm_0_19', 'fgm_20_29', 'fgm_30_39', 'fgm_40_49', 'fgm_50p', 'fum_rec', 'int', 'pass_2pt', 'pass_40p', 'pass_int', 'pass_td', 'pass_yd', 'pts_allow', 'rush_2pt', 'rush_40p', 'sack', 'safe', 'xpm']
K: 153 players, 23 stat keys
   mapped-but-absent: ['def_td', 'fgm', 'fgm_0_19', 'fgm_20_29', 'fgm_30_39', 'fum_lost', 'fum_rec', 'int', 'pass_2pt', 'pass_40p', 'pass_int', 'pass_td', 'pass_yd', 'pts_allow', 'rec', 'rec_2pt', 'rec_40p', 'rec_fd', 'rec_td', 'rec_yd', 'rush_2pt', 'rush_40p', 'rush_att', 'rush_fd', 'rush_td', 'rush_yd', 'sack', 'safe']
DST: 32 players, 25 stat keys
   mapped-but-absent: ['def_td', 'fgm', 'fgm_0_19', 'fgm_20_29', 'fgm_30_39', 'fgm_40_49', 'fgm_50p', 'fum_lost', 'pass_2pt', 'pass_40p', 'pass_int', 'pass_td', 'pass_yd', 'pts_allow', 'rec', 'rec_2pt', 'rec_40p', 'rec_fd', 'rec_td', 'rec_yd', 'rush_2pt', 'rush_40p', 'rush_att', 'rush_fd', 'rush_td', 'rush_yd', 'safe', 'xpm']

Available but unused (42): ['adp_2qb', 'adp_dynasty', 'adp_dynasty_2qb', 'adp_dynasty_half_ppr', 'adp_dynasty_ppr', 'adp_dynasty_std', 'adp_idp', 'adp_idp_1qb', 'adp_ppr', 'adp_rookie', 'adp_std', 'blk_kick', 'bonus_rec_rb', 'bonus_rec_te', 'bonus_rec_wr', 'bonus_rush_td_qb', 'cmp_pct', 'def_fum_td', 'def_kr_td', 'fgm_yds', 'fgmiss_40_49', 'fgmiss_50p', 'idp_fum_rec', 'idp_int', 'idp_tkl', 'idp_tkl_ast', 'idp_tkl_solo', 'pass_att', 'pass_cmp', 'pass_fd', 'pass_int_td', 'pr_td', 'pts_allow_0', 'pts_ppr', 'pts_std', 'rec_0_4', 'rec_10_19', 'rec_20_29', 'rec_30_39', 'rec_5_9', 'xpmiss', 'yds_allow_0_100']

players with half-PPR ADP: 790
FantasyPros ECR: 865 players (as of 8/20)
snapshots saved: projections_2026-08-20.csv, adp_2026-08-20.csv
rush_fd populated for 100% of 136 QB/RB with 20+ carries -> RUSH_FD_OK=True

In [4]:
def probe(url):
    r = requests.get(url, headers=HEADERS, timeout=30)
    soup = BeautifulSoup(r.text, "html.parser")
    print("Requested :", url)
    print("Final URL :", r.url)                      # reveals redirects
    print("Status/size:", r.status_code, "/", len(r.text), "bytes")
    print("Title     :", soup.title.get_text(strip=True) if soup.title else "none")
    print("Tables    :", [(t.get("id"), " ".join(t.get("class", [])), len(t.find_all("tr")))
                          for t in soup.find_all("table")])
    for key in ("ecrData", "adpData", "__NEXT_DATA__", "__NUXT__"):
        if key in r.text:
            print("Embedded JSON:", key, "FOUND")
    print("-" * 60)

probe("https://www.fantasypros.com/nfl/projections/rb.php?week=draft&scoring=HALF")
probe("https://www.fantasypros.com/nfl/projections/rb.php?week=draft")
probe("https://www.fantasypros.com/nfl/adp/half-point-ppr-overall.php")
probe("https://www.fantasypros.com/nfl/adp/ppr-overall.php")

Requested : https://www.fantasypros.com/nfl/projections/rb.php?week=draft&scoring=HALF
Final URL : https://www.fantasypros.com/nfl/projections/rb.php?week=draft
Status/size: 200 / 303745 bytes
Title     : 2026 Half-PPR RB Projections - Consensus Fantasy Football Stats for Running Backs | FantasyPros
Tables    : [('data', 'table table--sticky-columns table-bordered table-striped table-hover', 12)]
------------------------------------------------------------
Requested : https://www.fantasypros.com/nfl/projections/rb.php?week=draft
Final URL : https://www.fantasypros.com/nfl/projections/rb.php?week=draft
Status/size: 200 / 303745 bytes
Title     : 2026 Half-PPR RB Projections - Consensus Fantasy Football Stats for Running Backs | FantasyPros
Tables    : [('data', 'table table--sticky-columns table-bordered table-striped table-hover', 12)]
------------------------------------------------------------
Requested : https://www.fantasypros.com/nfl/adp/half-point-ppr-overall.php
Final URL : https://www.fantasypros.com/nfl/adp/half-point-ppr-overall.php
Status/size: 200 / 324155 bytes
Title     : Average Draft Position (ADP) - Half PPR Leagues 2026 | FantasyPros
Tables    : [('experts', 'table table-bordered table-full table-striped table-hover', 4)]
------------------------------------------------------------
Requested : https://www.fantasypros.com/nfl/adp/ppr-overall.php
Final URL : https://www.fantasypros.com/nfl/adp/ppr-overall.php
Status/size: 200 / 325152 bytes
Title     : Average Draft Position (ADP) - PPR Leagues 2026 | FantasyPros
Tables    : [('experts', 'table table-bordered table-full table-striped table-hover', 6)]
------------------------------------------------------------

In [5]:
# ============================================================
# CELL 3b — PLAYER METADATA (age, experience, injury, depth chart)
# Sleeper's projection records carry a nested `player` object. We only
# used position/team/name from it; this grabs the rest.
# ============================================================
print("player object fields:", sorted((records[0].get("player") or {}).keys()))

META_FIELDS = ["age", "years_exp", "injury_status", "status",
               "depth_chart_order", "number", "height", "weight"]

meta = []
for rec in records:
    p = rec.get("player") or {}
    row = {"SLEEPER_ID": rec.get("player_id") or p.get("player_id")}
    for f in META_FIELDS:
        row[f.upper()] = p.get(f)
    meta.append(row)

meta = pd.DataFrame(meta).drop_duplicates("SLEEPER_ID")
proj = proj.merge(meta, on="SLEEPER_ID", how="left")

for c in ("AGE", "YEARS_EXP", "DEPTH_CHART_ORDER"):
    if c in proj.columns:
        proj[c] = pd.to_numeric(proj[c], errors="coerce")

print(f"\nage populated for {proj['AGE'].notna().mean():.0%} of players")
print(proj.groupby("POS")["AGE"].median().round(1))

player object fields: ['fantasy_positions', 'first_name', 'injury_body_part', 'injury_notes', 'injury_start_date', 'injury_status', 'last_name', 'metadata', 'news_updated', 'position', 'team', 'team_abbr', 'team_changed_at', 'years_exp']

age populated for 0% of players
POS
DST   NaN
K     NaN
QB    NaN
RB    NaN
TE    NaN
WR    NaN
Name: AGE, dtype: float64

In [6]:
# ============================================================
# CELL 3c — PLAYER METADATA (Sleeper) + AGE (nflverse)
# Sleeper's player object has no age field, so age comes from nflverse.
# Self-contained: defines its own loader.
# ============================================================
NFLVERSE = "https://github.com/nflverse/nflverse-data/releases/download"

def load_first(candidates, label):
    """Try candidate URLs in order; return the first that loads."""
    for url in candidates:
        try:
            df = (pd.read_parquet(url) if url.endswith(".parquet")
                  else pd.read_csv(url, low_memory=False))
            print(f"OK  {label}: {url.split('/')[-1]}  ({len(df):,} rows)")
            return df
        except Exception as e:
            print(f"    no: {url.split('/')[-1]}  ({type(e).__name__})")
    raise RuntimeError(f"could not load {label}")

# ---- 1. metadata Sleeper actually provides ----
META_FIELDS = ["years_exp", "injury_status", "injury_body_part",
               "injury_notes", "team_changed_at"]

meta = []
for rec in records:
    p = rec.get("player") or {}
    row = {"SLEEPER_ID": rec.get("player_id") or p.get("player_id")}
    for f in META_FIELDS:
        row[f.upper()] = p.get(f)
    meta.append(row)

meta = pd.DataFrame(meta).drop_duplicates("SLEEPER_ID")
proj = proj.drop(columns=[f.upper() for f in META_FIELDS], errors="ignore")
proj = proj.merge(meta, on="SLEEPER_ID", how="left")
proj["YEARS_EXP"] = pd.to_numeric(proj["YEARS_EXP"], errors="coerce")
print(f"years_exp populated for {proj['YEARS_EXP'].notna().mean():.0%} of players")

# ---- 2. age from nflverse ----
def _norm(n):
    n = str(n).lower().replace(".", "").replace("'", "")
    n = re.sub(r"\s+(jr|sr|ii|iii|iv|v)$", "", n)
    return re.sub(r"\s+", " ", n).strip()

ros = load_first([
    f"{NFLVERSE}/players/players.parquet",          # all players, year-independent
    f"{NFLVERSE}/rosters/roster_2025.parquet",
    f"{NFLVERSE}/rosters/rosters_2025.parquet",
    f"{NFLVERSE}/rosters/roster_2024.parquet",
], "player birth dates")

print("name/birth columns:",
      [c for c in ros.columns if "name" in c.lower() or "birth" in c.lower()])

namecol = next((c for c in ("display_name", "player_name", "full_name", "football_name")
                if c in ros.columns), None)
birthcol = next((c for c in ("birth_date", "birthdate") if c in ros.columns), None)
if namecol is None or birthcol is None:
    raise RuntimeError(f"unexpected roster schema — columns: {list(ros.columns)[:40]}")

ros = ros[[namecol, birthcol]].dropna()
ros[birthcol] = pd.to_datetime(ros[birthcol], errors="coerce")
ros["AGE"] = (pd.Timestamp("2026-09-01") - ros[birthcol]).dt.days / 365.25
ros = ros[(ros["AGE"] > 18) & (ros["AGE"] < 50)]          # drop bad birth dates
ros["_k"] = ros[namecol].map(_norm)
ros = ros.drop_duplicates("_k")[["_k", "AGE"]]

proj["_k"] = proj["Player"].map(_norm)
proj = proj.drop(columns=["AGE"], errors="ignore").merge(ros, on="_k", how="left")

drafted = proj[proj["ADP_HALF"].notna()]
print(f"\nage matched for {proj['AGE'].notna().mean():.0%} of all players, "
      f"{drafted['AGE'].notna().mean():.0%} of players with ADP")
print(drafted.groupby("POS")["AGE"].median().round(1))

years_exp populated for 99% of players
OK  player birth dates: players.parquet  (25,048 rows)
name/birth columns: ['display_name', 'common_first_name', 'first_name', 'last_name', 'short_name', 'football_name', 'birth_date', 'college_name']

age matched for 72% of all players, 89% of players with ADP
POS
DST     NaN
K      28.8
QB     28.5
RB     26.7
TE     27.3
WR     26.3
Name: AGE, dtype: float64

In [7]:
# ============================================================
# CELL 4 — CUSTOM SCORING ON REAL PROJECTED STATS  (complete)
#
# Skill positions are scored from raw stats with your exact league
# settings. K and DST fall back to Sleeper's own scoring because the
# payload omits the components we'd need (no fgm total, no pts_allow) —
# and VOR spread at those two positions is small enough that the
# approximation costs nothing on draft day.
#
# Categories your league pays for but Sleeper does NOT project:
#   rush_40p (40+ yard runs, 2 pts) and pass_40p (40+ completions, 1 pt)
#   are absent for every position, so those terms contribute 0. They're
#   left in the formula so they start counting automatically if Sleeper
#   ever adds them. rec_40p IS projected and is credited.
# Also unmodeled (need TD-level detail no source breaks out): 40+ yard
#   TD bonuses, return TDs, offensive fumble return TDs, pick-six extra
#   penalty, missed FG 0-19.
# ============================================================
def score_row(row):
    def g(col):
        """Safe stat read: missing or NaN -> 0.0. Without the NaN guard a
        single blank field would silently turn PROJ_PTS into NaN and drop
        the player out of the VOR ordering entirely."""
        v = row.get(col, 0.0)
        try:
            v = float(v)
        except (TypeError, ValueError):
            return 0.0
        return 0.0 if pd.isna(v) else v

    # --- kickers and team defenses: use Sleeper's own points ---
    if row["POS"] in ("K", "DST"):
        return g("SLEEPER_PTS_HALF")

    # --- rushing first downs: real projection, estimate only as fallback ---
    rush_fd = (g("RUSH_FD") if RUSH_FD_OK
               else g("RUSH_YD") * RUSH_1D_RATES.get(row["POS"], 0.0))

    return (
        # passing
        g("PASS_YD") * SCORING["pass_yd"]
        + g("PASS_TD") * SCORING["pass_td"]
        + g("INT") * SCORING["int"]
        + g("PASS_40P") * SCORING["pass_40p"]        # not projected -> 0
        # rushing
        + g("RUSH_YD") * SCORING["rush_yd"]
        + g("RUSH_TD") * SCORING["rush_td"]
        + rush_fd * SCORING["rush_fd"]
        + g("RUSH_40P") * SCORING["rush_40p"]        # not projected -> 0
        # receiving
        + g("REC") * SCORING["rec"]
        + g("REC_YD") * SCORING["rec_yd"]
        + g("REC_TD") * SCORING["rec_td"]
        + g("REC_40P") * SCORING["rec_40p"]
        # misc
        + g("FL") * SCORING["fumble"]
        + (g("PASS_2PT") + g("RUSH_2PT") + g("REC_2PT")) * SCORING["two_pt"]
    )


proj["PROJ_PTS"] = proj.apply(score_row, axis=1).round(1)

# --- sanity check: top of each position should look plausible ---
for pos in POSITIONS:
    top = (proj[proj["POS"] == pos]
           .nlargest(3, "PROJ_PTS")[["Player", "PROJ_PTS"]]
           .to_string(index=False, header=False)
           .replace("\n", " | "))
    print(f"{pos:>4}: {top}")

  QB:    Josh Allen 442.2 | Lamar Jackson 413.4 |    Drake Maye 399.6
  RB:    Jahmyr Gibbs 368.8 |  Bijan Robinson 367.9 | Jonathan Taylor 327.2
  WR:         Puka Nacua 272.4 |      Ja'Marr Chase 268.3 | Jaxon Smith-Njigba 246.6
  TE:     Brock Bowers 213.6 |     Trey McBride 196.5 | Colston Loveland 182.0
   K:   Brandon Aubrey 116.0 | Ka'imi Fairbairn 113.0 |       Cam Little 112.0
 DST: Los Angeles Rams 106.0 |   Houston Texans 104.0 | Seattle Seahawks 103.0

In [8]:
# ============================================================
# CELL 6 — REPLACEMENT LEVELS + VOR
# Replacement rank is derived from roster structure and recomputed
# from live data every run:
#   last starter = teams x slots + this position's share of flexes
#   replacement  = the next player down
# For this league: QB13, RB31, WR43, TE13, K13, DST13.
# ============================================================
def replacement_ranks():
    out = {}
    for pos in POSITIONS:
        starters = ROSTER["teams"] * ROSTER["slots"].get(pos, 0)
        flex = (round(ROSTER["teams"] * ROSTER["flex"] * ROSTER["flex_split"].get(pos, 0.0))
                if pos in ("RB", "WR", "TE") else 0)
        out[pos] = REPLACEMENT_OVERRIDE.get(pos, starters + flex + 1)
    return out

repl_rank = replacement_ranks()
repl_pts = {}
for pos in POSITIONS:
    pool = proj.loc[proj["POS"] == pos].sort_values("PROJ_PTS", ascending=False)
    if len(pool) == 0:
        repl_pts[pos] = 0.0
        continue
    idx = min(repl_rank[pos] - 1, len(pool) - 1)      # clamp if pool is shallow
    repl_pts[pos] = float(pool["PROJ_PTS"].iloc[idx])

print("replacement levels:",
      {p: f"{p}{repl_rank[p]} = {repl_pts[p]:.1f} pts" for p in POSITIONS})

proj["VOR"] = proj.apply(lambda r: r["PROJ_PTS"] - repl_pts[r["POS"]], axis=1).round(1)
proj = proj.sort_values("VOR", ascending=False).reset_index(drop=True)
proj["VOR_RANK"] = proj.index + 1
proj["POS_RANK"] = proj.groupby("POS")["PROJ_PTS"].rank(ascending=False,
                                                        method="first").astype(int)

replacement levels: {'QB': 'QB13 = 364.2 pts', 'RB': 'RB34 = 177.4 pts', 'WR': 'WR40 = 146.7 pts', 'TE': 'TE13 = 135.8 pts', 'K': 'K13 = 103.0 pts', 'DST': 'DST13 = 86.0 pts'}

In [9]:
# ============================================================
# CELL 7 — TIERS (gap-based, per position)
# A new tier starts wherever the drop to the next player is unusually
# large (> 1.25x the average gap near the top of the position, with a
# 4-point floor so flat tails don't fragment). Draft by tier: "how many
# are left in this tier vs. the next tier at another position?"
# ============================================================
def assign_tiers(points_desc):
    n = len(points_desc)
    if n == 0:
        return []
    gaps = [points_desc[i - 1] - points_desc[i] for i in range(1, min(n, 40))]
    mean_gap = sum(gaps) / len(gaps) if gaps else 0.0
    threshold = max(mean_gap * 1.25, 4.0)
    tiers, tier = [1], 1
    for i in range(1, n):
        if points_desc[i - 1] - points_desc[i] > threshold:
            tier += 1
        tiers.append(tier)
    return tiers

proj["TIER"] = 0
for pos in POSITIONS:
    pool = proj.loc[proj["POS"] == pos].sort_values("PROJ_PTS", ascending=False)
    proj.loc[pool.index, "TIER"] = assign_tiers(pool["PROJ_PTS"].tolist())

In [10]:
# ============================================================
# CELL 8 — MERGE ADP + FANTASYPROS ECR
# Sleeper omits name suffixes (Jr./Sr./II/III); FantasyPros includes
# them, so both sides are matched on a normalized key. Two passes:
# name+position first, then name-only for anyone left (position
# disagreements between sources are common for hybrid players).
# ============================================================
def _norm(n):
    n = str(n).lower().replace(".", "").replace("'", "").replace("-", " ")
    n = re.sub(r"\s+(jr|sr|ii|iii|iv|v)$", "", n)
    return re.sub(r"\s+", " ", n).strip()

# manual overrides for genuine name differences (nicknames, etc.)
# key = normalized Sleeper name, value = normalized FantasyPros name
NAME_ALIASES = {
    # "hollywood brown": "marquise brown",
}

# --- ADP (same source as projections, so plain names are safe) ---
board = proj.merge(adp[["Player", "POS", "ADP_RANK", "AVG"]],
                   on=["Player", "POS"], how="left")

# --- FantasyPros ECR overlay ---
if fp is not None:
    board["_k"] = board["Player"].map(_norm).replace(NAME_ALIASES)
    fp = fp.copy()
    fp["_k"] = fp["Player"].map(_norm)

    fp_kp = fp.dropna(subset=["_k"]).drop_duplicates(["_k", "POS"]).set_index(["_k", "POS"])
    fp_k = fp.dropna(subset=["_k"]).drop_duplicates("_k").set_index("_k")
    FP_COLS = ["ECR", "FP_TIER", "Bye"]

    # pass 1: normalized name + position
    idx = pd.MultiIndex.from_arrays([board["_k"], board["POS"]])
    for c in FP_COLS:
        board[c] = fp_kp[c].reindex(idx).values

    # pass 2: normalized name only, for whatever pass 1 missed
    miss = board["ECR"].isna()
    for c in FP_COLS:
        board.loc[miss, c] = fp_k[c].reindex(board.loc[miss, "_k"]).values

    matched = board["ECR"].notna()
    print(f"ECR matched: {int(matched.sum())} of {len(board)} players")

    still = board[board["ADP_RANK"].notna() & (board["ADP_RANK"] <= 170)
                  & board["ECR"].isna()]
    if len(still):
        print(f"\n[!] {len(still)} top-170 players STILL missing ECR "
              f"(add to NAME_ALIASES if these are real players):")
        print(still[["Player", "POS", "Team", "ADP_RANK"]]
              .sort_values("ADP_RANK").to_string(index=False))
    else:
        print("all top-170 ADP players matched an ECR ✔")
else:
    board["ECR"] = float("nan")
    board["FP_TIER"] = float("nan")
    board["Bye"] = None

# --- draft-day value columns ---
# VALUE  = vs Sleeper ADP (sharp drafters)
# ROOM+  = vs FantasyPros ECR (closest proxy for your Yahoo room's board)
board["VALUE"] = (board["ADP_RANK"] - board["VOR_RANK"]).round(0)
board["ROOM+"] = (board["ECR"] - board["VOR_RANK"]).round(0)

ECR matched: 853 of 3226 players

[!] 1 top-170 players STILL missing ECR (add to NAME_ALIASES if these are real players):
        Player POS Team  ADP_RANK
Jayden Higgins  WR  HOU     140.0

In [19]:
# ============================================================
# CELL 8b — EMPIRICAL AVAILABILITY (games played by position + age)
#
# Sleeper projects a flat 18 games for everyone, so availability has to
# come from history. Two things make this non-trivial:
#
#   1. POPULATION. nflverse weekly data includes every fringe player who
#      ever recorded a stat, so a raw positional mean measures "games a
#      random NFL body plays" (~10 of 17), not "games a draftable starter
#      plays" (~13-16). We condition on a draftable cohort instead.
#
#   2. SELECTION. The cohort must be defined EX-ANTE. Filtering on the
#      same season's production would drop the Week-1 ACL tear — exactly
#      the outcome we're trying to measure — and bias availability up.
#      So the cohort for season Y is the top-N at each position in Y-1,
#      and players who then missed all of Y are kept as genuine zeros.
#
# Note: `games` conflates injury with losing your job. That's intended —
# a benched starter is equally useless to you, and VOR_ADJ backfills
# either case from waivers. Read the output as "expected games as a
# useful starter," not as an injury forecast.
#
# Slow cell: downloads ~5 seasons of weekly data. Run once.
# ============================================================
SEASONS = [2021, 2022, 2023, 2024, 2025]        # 17-game era only

wk = []
for y in SEASONS:
    try:
        d = load_first([
            f"{NFLVERSE}/player_stats/player_stats_{y}.parquet",
            f"{NFLVERSE}/stats_player/stats_player_week_{y}.parquet",
        ], f"weekly {y}")
        d["season"] = y
        wk.append(d)
    except Exception as e:
        print(f"skip {y}: {e}")
wk = pd.concat(wk, ignore_index=True)

pcol = "position" if "position" in wk.columns else "position_group"
ncol = "player_display_name" if "player_display_name" in wk.columns else "player_name"
ptscol = "fantasy_points_ppr" if "fantasy_points_ppr" in wk.columns else "fantasy_points"
SKILL = ["QB", "RB", "WR", "TE"]

# games actually played, per player-season (also used by Cell 8c)
gp = (wk[wk[pcol].isin(SKILL)]
      .groupby([ncol, pcol, "season"])["week"].nunique().reset_index(name="games"))

# season fantasy totals -> positional rank, for defining the cohort
season_pts = (wk[wk[pcol].isin(SKILL)]
              .groupby([ncol, pcol, "season"], as_index=False)[ptscol].sum())
season_pts["pos_rank"] = (season_pts.groupby([pcol, "season"])[ptscol]
                          .rank(ascending=False, method="first"))


def build_cohort(mult):
    """Cohort for season Y = top-N at position in Y-1, where N is this
    league's replacement rank scaled by `mult`. Returns one row per
    player-season with games played (0 if they never appeared)."""
    n = {p: max(int(repl_rank[p] * mult), 12) for p in SKILL}
    c = season_pts[season_pts["pos_rank"] <= season_pts[pcol].map(n)].copy()
    c["season"] += 1                                  # carry forward one year
    c = c[c["season"].isin(SEASONS)][[ncol, pcol, "season"]]
    c = c.merge(gp[[ncol, pcol, "season", "games"]],
                on=[ncol, pcol, "season"], how="left")
    c["games"] = c["games"].fillna(0.0)
    c["avail"] = c["games"] / 17.0
    return c, n


# ---- sensitivity: does the cohort threshold actually matter? ----
print("SENSITIVITY — availability rate by cohort width\n")
for m in (1.0, 1.5, 2.0, 3.0):
    c, n = build_cohort(m)
    rates = (c.groupby(pcol)["avail"].mean().round(3)).to_dict()
    print(f"  mult {m}: N={n}  ->  {rates}")
print("\n(if these barely move, the threshold doesn't matter; if RB slides as")
print(" the cohort widens, that's job-loss noise entering the sample)\n")

# ---- build the table at the chosen width ----
DRAFT_BUFFER = 1.5          # replacement rank x this = draftable pool
cohort, DRAFTABLE = build_cohort(DRAFT_BUFFER)
print(f"using DRAFT_BUFFER={DRAFT_BUFFER} -> {DRAFTABLE}")

# age at that season, from nflverse birth dates
pl = load_first([f"{NFLVERSE}/players/players.parquet"], "players")
pn = next(c for c in ("display_name", "player_name", "full_name") if c in pl.columns)
pl = pl[[pn, "birth_date"]].dropna().copy()
pl["birth_date"] = pd.to_datetime(pl["birth_date"], errors="coerce")
pl["_k"] = pl[pn].map(_norm)

cohort["_k"] = cohort[ncol].map(_norm)
cohort = cohort.merge(pl.drop_duplicates("_k")[["_k", "birth_date"]], on="_k", how="left")
cohort["age"] = ((pd.to_datetime(cohort["season"].astype(str) + "-09-01")
                  - cohort["birth_date"]).dt.days / 365.25)

BUCKETS = [(0, 26, "<26"), (26, 30, "26-30"), (30, 60, "30+")]
cohort["bucket"] = pd.cut(cohort["age"], [b[0] for b in BUCKETS] + [60],
                          labels=[b[2] for b in BUCKETS], right=False)

print("\nGAMES PLAYED BY DRAFTABLE STARTERS (of 17):")
print(cohort.groupby(pcol)["games"].describe()[["count", "mean", "50%", "min"]].round(1))

tbl = (cohort.dropna(subset=["bucket"])
       .groupby([pcol, "bucket"], observed=True)["avail"]
       .agg(["mean", "count"]).round(3))
print("\nAVAILABILITY BY POSITION AND AGE:")
print(tbl)

# buckets thinner than 25 observations fall back to the position mean
MIN_COUNT = 15          # coarser bands mean fewer, better-populated cells
AVAIL = {(p, b): r["mean"] for (p, b), r in tbl.iterrows() if r["count"] >= MIN_COUNT}
POS_MEAN = cohort.groupby(pcol)["avail"].mean().to_dict()
print(f"\nusable buckets: {len(AVAIL)} of {len(tbl)}")
print("position means:", {k: round(v, 3) for k, v in POS_MEAN.items()})
print("age matched for", f"{cohort['age'].notna().mean():.0%}", "of cohort")

OK  weekly 2021: player_stats_2021.parquet  (5,698 rows)
OK  weekly 2022: player_stats_2022.parquet  (5,631 rows)
OK  weekly 2023: player_stats_2023.parquet  (5,653 rows)
OK  weekly 2024: player_stats_2024.parquet  (5,597 rows)
    no: player_stats_2025.parquet  (HTTPError)
OK  weekly 2025: stats_player_week_2025.parquet  (19,422 rows)
SENSITIVITY — availability rate by cohort width

  mult 1.0: N={'QB': 13, 'RB': 34, 'WR': 40, 'TE': 13}  ->  {'QB': 0.876, 'RB': 0.782, 'TE': 0.852, 'WR': 0.835}
  mult 1.5: N={'QB': 19, 'RB': 51, 'WR': 60, 'TE': 19}  ->  {'QB': 0.838, 'RB': 0.782, 'TE': 0.836, 'WR': 0.79}
  mult 2.0: N={'QB': 26, 'RB': 68, 'WR': 80, 'TE': 26}  ->  {'QB': 0.768, 'RB': 0.707, 'TE': 0.799, 'WR': 0.765}
  mult 3.0: N={'QB': 39, 'RB': 102, 'WR': 120, 'TE': 39}  ->  {'QB': 0.664, 'RB': 0.57, 'TE': 0.754, 'WR': 0.676}

(if these barely move, the threshold doesn't matter; if RB slides as
 the cohort widens, that's job-loss noise entering the sample)

using DRAFT_BUFFER=1.5 -> {'QB': 19, 'RB': 51, 'WR': 60, 'TE': 19}
OK  players: players.parquet  (25,048 rows)

GAMES PLAYED BY DRAFTABLE STARTERS (of 17):
          count  mean   50%  min
position
QB         76.0  14.2  16.0  0.0
RB        204.0  13.3  16.0  0.0
TE         76.0  14.2  15.0  0.0
WR        240.0  13.4  16.0  0.0

AVAILABILITY BY POSITION AND AGE:
                  mean  count
position bucket
QB       <26     0.837     22
         26-30   0.873     24
         30+     0.812     30
RB       <26     0.799     89
         26-30   0.802     87
         30+     0.635     24
TE       <26     0.849     21
         26-30   0.889     36
         30+     0.721     19
WR       <26     0.852     99
         26-30   0.767     90
         30+     0.712     51

usable buckets: 12 of 12
position means: {'QB': 0.838, 'RB': 0.782, 'TE': 0.836, 'WR': 0.79}
age matched for 99% of cohort

In [12]:
# ============================================================
# CELL 8c — AVAILABILITY-ADJUSTED VOR  (display only)
#
# Missed games are backfilled from waivers at replacement level, which
# contributes zero VOR by definition. So expected value from the roster
# spot is G*(p - r), and since raw VOR is 18*(p - r):
#       VOR_ADJ = VOR * (expected_games / 18)
# Availability scales VOR, not points. VOR remains the primary ranking;
# VOR_ADJ is a second read on who is carrying risk.
# ============================================================
def _bucket(a):
    if pd.isna(a):
        return None
    for lo, hi, lab in BUCKETS:
        if lo <= a < hi:
            return lab
    return None

def _avail(pos, age):
    if pos in ("K", "DST"):
        return 1.0                      # streamed weekly; no availability drag
    b = _bucket(age)
    if b is not None and (pos, b) in AVAIL:
        return AVAIL[(pos, b)]
    return POS_MEAN.get(pos, 0.88)

board["EXP_AVAIL"] = [_avail(p, a) for p, a in zip(board["POS"], board["AGE"])]
board["EXP_GAMES"] = (board["EXP_AVAIL"] * 18).round(1)
board["VOR_ADJ"] = (board["VOR"] * board["EXP_AVAIL"]).round(1)

# strongest per-player signal: games actually played last season
last = gp[gp["season"] == 2025].drop_duplicates("_k").set_index("_k")["games"]
board["GP_2025"] = last.reindex(board["_k"]).values

# who moves most once availability is priced in
mv = board[board["ADP_RANK"].notna()].copy()
mv["ADJ_RANK"] = mv["VOR_ADJ"].rank(ascending=False, method="first")
mv["DROP"] = (mv["ADJ_RANK"] - mv["VOR_RANK"]).round(0)
print("BIGGEST AVAILABILITY DISCOUNTS (fall furthest when risk is priced in):")
print(mv.nlargest(15, "DROP")[
    ["Player", "POS", "AGE", "VOR", "VOR_ADJ", "EXP_GAMES", "GP_2025", "DROP"]
].to_string(index=False))

BIGGEST AVAILABILITY DISCOUNTS (fall furthest when risk is priced in):
             Player POS       AGE    VOR  VOR_ADJ  EXP_GAMES  GP_2025  DROP
  Noah Rauschenberg   K       NaN -103.0   -103.0       18.0      NaN 282.0
      James McCourt   K 28.810404 -103.0   -103.0       18.0      NaN 281.0
         Trey Wolff   K       NaN -103.0   -103.0       18.0      NaN 279.0
        Kai Forbath   K 38.997947 -103.0   -103.0       18.0      NaN 278.0
       Alex Kessman   K 28.662560 -103.0   -103.0       18.0      NaN 266.0
         Dan Bailey   K 38.598220 -103.0   -103.0       18.0      NaN 266.0
       Chris Naggar   K 28.728268 -103.0   -103.0       18.0      NaN 266.0
       Andrew Mevis   K       NaN -103.0   -103.0       18.0      NaN 263.0
    Spencer Shrader   K 27.288159 -103.0   -103.0       18.0      NaN 259.0
     Adam Vinatieri   K       NaN -103.0   -103.0       18.0      NaN 251.0
       Quinn Nordin   K 28.043806 -103.0   -103.0       18.0      NaN 250.0
          Cade York   K 25.593429  -90.0    -90.0       18.0      NaN 241.0
   Kansei Matsuzawa   K 27.646817 -103.0   -103.0       18.0      NaN 237.0
Rodrigo Blankenship   K 29.587953 -103.0   -103.0       18.0      NaN 236.0
      Jack Podlesny   K       NaN -103.0   -103.0       18.0      NaN 236.0

In [20]:
# ============================================================
# CELL 9 — FINAL DRAFT SHEET
# VOR is the ranking. VOR_ADJ / EXP_GAMES are the availability read.
# ============================================================
SHEET_COLS = ["VOR_RANK", "Player", "POS", "POS_RANK", "Team", "AGE", "Bye", "TIER",
              "PROJ_PTS", "VOR", "VOR_ADJ", "EXP_GAMES",
              "ADP_RANK", "VALUE", "ECR", "ROOM+"]
sheet = board[[c for c in SHEET_COLS if c in board.columns]]

pd.set_option("display.max_rows", 250)
pd.set_option("display.width", 200)
sheet.head(200)

     VOR_RANK                  Player  POS  POS_RANK Team        AGE   Bye  TIER  PROJ_PTS    VOR  VOR_ADJ  EXP_GAMES  ADP_RANK  VALUE    ECR  ROOM+
0           1            Jahmyr Gibbs   RB         1  DET  24.451745     6     1     368.8  191.4    116.2       10.9       1.0    0.0    1.0    0.0
1           2          Bijan Robinson   RB         2  ATL  24.585900    11     1     367.9  190.5    115.6       10.9       2.0    0.0    2.0    0.0
2           3         Jonathan Taylor   RB         3  IND  27.616701    13     2     327.2  149.8     89.3       10.7       5.0    2.0    7.0    4.0
3           4     Christian McCaffrey   RB         4   SF  30.234086     8     3     312.2  134.8     88.0       11.8       6.0    2.0    8.0    4.0
4           5              James Cook   RB         5  BUF  26.934976     7     3     311.9  134.5     80.2       10.7       9.0    4.0   11.0    6.0
5           6           Derrick Henry   RB         6  BAL  32.657084    13     3     310.4  133.0     69.7        9.4      18.0   12.0   22.0   16.0
6           7              Puka Nacua   WR         1  LAR  25.259411    11     1     272.4  125.7     69.5       10.0       4.0   -3.0    4.0   -3.0
7           8           Ja'Marr Chase   WR         2  CIN  26.502396     6     2     268.3  121.6     71.1       10.5       3.0   -5.0    3.0   -5.0
8           9           Ashton Jeanty   RB         7   LV  22.748802    13     4     297.1  119.7     68.8       10.4      11.0    2.0   12.0    3.0
9          10           De'Von Achane   RB         8  MIA  24.884326     6     4     293.8  116.4     70.7       10.9      14.0    4.0   18.0    8.0
10         11          Saquon Barkley   RB         9  PHI  29.557837    10     4     292.9  115.5     70.1       10.9      12.0    1.0   16.0    5.0
11         12          Kenneth Walker   RB        10   KC  25.864476     5     4     287.1  109.7     66.6       10.9      17.0    5.0   21.0    9.0
12         13             Chase Brown   RB        11  CIN  26.447639     6     5     279.6  102.2     60.9       10.7      16.0    3.0   14.0    1.0
13         14      Jaxon Smith-Njigba   WR         3  SEA  24.544832    11     3     246.6   99.9     55.2       10.0       7.0   -7.0    5.0   -9.0
14         15         Omarion Hampton   RB        12  LAC  23.463381     7     5     275.0   97.6     56.1       10.4      15.0    0.0   20.0    5.0
15         16       Amon-Ra St. Brown   WR         4  DET  26.855578     6     4     238.9   92.2     53.9       10.5       8.0   -8.0    6.0  -10.0
16         17             CeeDee Lamb   WR         5  DAL  27.400411    14     5     232.9   86.2     50.4       10.5      10.0   -7.0    9.0   -8.0
17         18            Nico Collins   WR         6  HOU  27.455168     8     5     229.3   82.6     48.3       10.5      23.0    5.0   19.0    1.0
18         19              Josh Allen   QB         1  BUF  34.672142     7     1     442.2   78.0     41.3        9.5      22.0    3.0   27.0    8.0
19         20            Brock Bowers   TE         1   LV  23.718001    13     1     213.6   77.8     45.3       10.5      21.0    1.0   17.0   -3.0
20         21              A.J. Brown   WR         7   NE  29.171800    11     6     215.9   69.2     43.2       11.2      19.0   -2.0   15.0   -6.0
21         22             Breece Hall   RB        13  NYJ  25.253936    13     6     245.5   68.1     41.3       10.9      30.0    8.0   35.0   13.0
22         23        Justin Jefferson   WR         8  MIN  27.211499     6     6     214.7   68.0     39.8       10.5      13.0  -10.0   10.0  -13.0
23         24            Drake London   WR         9  ATL  25.106092    11     6     214.5   67.8     37.5       10.0      20.0   -4.0   13.0  -11.0
24         25          George Pickens   WR        10  DAL  25.494867    14     6     214.0   67.3     37.2       10.0      26.0    1.0   23.0   -2.0
25         26          Kyren Williams   RB        14  LAR  26.015058    11     6     244.3   66.9     39.9       10.7      27.0    1.0   31.0    5.0
26         27        Javonte Williams   RB        15  DAL  26.351814    14     6     242.7   65.3     38.9       10.7      33.0    6.0   34.0    7.0
27         28        David Montgomery   RB        16  HOU  29.234771     8     6     242.6   65.2     39.6       10.9      49.0   21.0   56.0   28.0
28         29           D'Andre Swift   RB        17  CHI  27.630390    10     6     242.1   64.7     38.6       10.7      52.0   23.0   50.0   21.0
29         30          Travis Etienne   RB        18   NO  27.597536     8     6     240.8   63.4     37.8       10.7      41.0   11.0   45.0   15.0
30         31            Trey McBride   TE         2  ARI  26.776181    14     2     196.5   60.7     33.6       10.0      24.0   -7.0   24.0   -7.0
31         32          Jeremiyah Love   RB        19  ARI  21.253936    14     6     237.8   60.4     34.7       10.4      25.0   -7.0   40.0    8.0
32         33             Josh Jacobs   RB        20   GB  28.553046    11     6     235.3   57.9     35.1       10.9      29.0   -4.0   36.0    3.0
33         34             Chris Olave   WR        11   NO  26.179329     8     7     203.4   56.7     33.2       10.5      32.0   -2.0   25.0   -9.0
34         35        Quinshon Judkins   RB        21  CLE  22.841889    11     6     233.8   56.4     32.4       10.4      46.0   11.0   54.0   19.0
35         36            Cam Skattebo   RB        22  NYG  24.569473     8     6     229.0   51.6     31.3       10.9      37.0    1.0   51.0   15.0
36         37           DeVonta Smith   WR        12  PHI  27.797399    10     8     197.5   50.8     29.7       10.5      34.0   -3.0   29.0   -8.0
37         38            Bucky Irving   RB        23   TB  24.035592    10     6     228.0   50.6     30.7       10.9      45.0    7.0   55.0   17.0
38         39             Zay Flowers   WR        13  BAL  25.971253    13     8     197.2   50.5     27.9       10.0      42.0    3.0   30.0   -9.0
39         40           Ladd McConkey   WR        14  LAC  24.804928     7     8     196.4   49.7     27.5       10.0      40.0    0.0   39.0   -1.0
40         41           Lamar Jackson   QB         2  BAL  29.648186    13     2     413.4   49.2     23.5        8.6      35.0   -6.0   38.0   -3.0
41         42             Rashee Rice   WR        15   KC  26.360027     5     8     195.6   48.9     28.6       10.5      28.0  -14.0   26.0  -16.0
42         43            Malik Nabers   WR        16  NYG  23.096509     8     8     195.3   48.6     32.0       11.9      31.0  -12.0   28.0  -15.0
43         44             Tee Higgins   WR        17  CIN  27.619439     6     8     194.7   48.0     28.1       10.5      38.0   -6.0   33.0  -11.0
44         45            Emeka Egbuka   WR        18   TB  23.882272    10     8     194.2   47.5     31.3       11.9      39.0   -6.0   41.0   -4.0
45         46              Mike Evans   WR        19   SF  33.029432     8     8     194.2   47.5     30.0       11.4      60.0   14.0   59.0   13.0
46         47        Colston Loveland   TE         3  CHI  22.395619    10     3     182.0   46.2     26.9       10.5      44.0   -3.0   43.0   -4.0
47         48       Tetairoa McMillan   WR        20  CAR  23.408624     5     8     192.5   45.8     30.2       11.9      36.0  -12.0   32.0  -16.0
48         49          Garrett Wilson   WR        21  NYJ  26.110883    13     8     192.5   45.8     26.8       10.5      43.0   -6.0   37.0  -12.0
49         50           Jaylen Waddle   WR        22  DEN  27.767283    10     8     191.1   44.4     26.0       10.5      47.0   -3.0   42.0   -8.0
50         51       Parker Washington   WR        23  JAX  24.449008     7     9     186.5   39.8     22.0       10.0      75.0   24.0   67.0   16.0
51         52          Terry McLaurin   WR        24  WAS  30.962355     7     9     184.6   37.9     22.0       10.4      54.0    2.0   46.0   -6.0
52         53        Jameson Williams   WR        25  DET  25.434634     6     9     184.4   37.7     20.8       10.0      57.0    4.0   52.0   -1.0
53         54           Luther Burden   WR        26  CHI  22.721424    10     9     183.2   36.5     24.1       11.9      55.0    1.0   48.0   -6.0
54         55        Christian Watson   WR        27   GB  27.307324    11     9     183.1   36.4     21.3       10.5      68.0   13.0   57.0    2.0
55         56              Drake Maye   QB         3   NE  24.005476    11     3     399.6   35.4     18.8        9.5      51.0   -5.0   44.0  -12.0
56         57             Rome Odunze   WR        28  CHI  24.246407    10     9     181.0   34.3     19.0       10.0      62.0    5.0   60.0    3.0
57         58            Tyler Warren   TE         4  IND  24.273785    13     4     168.9   33.1     16.6        9.1      50.0   -8.0   53.0   -5.0
58         59          Jadarian Price   RB        24  SEA  22.896646    11     7     208.0   30.6     17.6       10.4      61.0    2.0   65.0    6.0
59         60             Sam LaPorta   TE         5  DET  25.634497     6     4     166.2   30.4     15.3        9.1      64.0    4.0   78.0   18.0
60         61             Jayden Reed   WR        29   GB  26.343600    11    10     173.8   27.1     15.9       10.5     103.0   42.0  109.0   48.0
61         62            Brian Thomas   WR        30  JAX  23.898700     7    10     171.4   24.7     16.3       11.9      70.0    8.0   74.0   12.0
62         63          Bhayshul Tuten   RB        25  JAX  24.544832     7     7     201.7   24.3     14.8       10.9      59.0   -4.0   63.0    0.0
63         64          Jayden Daniels   QB         4  WAS  25.702943     7     4     385.0   20.8     11.0        9.5      65.0    1.0   61.0   -3.0
64         65           Davante Adams   WR        31  LAR  33.686516    11    11     167.3   20.6     13.0       11.4      58.0   -7.0   47.0  -18.0
65         66        Los Angeles Rams  DST         1  LAR        NaN    11     1     106.0   20.0     20.0       18.0     132.0   66.0  187.0  121.0
66         67     Rhamondre Stevenson   RB        26   NE  28.520192    11     7     196.7   19.3     11.7       10.9      77.0   10.0   73.0    6.0
67         68          Houston Texans  DST         2  HOU        NaN     8     1     104.0   18.0     18.0       18.0     133.0   65.0  178.0  110.0
68         69      TreVeyon Henderson   RB        27   NE  23.860370    11     7     195.0   17.6     10.1       10.4      48.0  -21.0   64.0   -5.0
69         70        Seattle Seahawks  DST         3  SEA        NaN    11     1     103.0   17.0     17.0       18.0     134.0   64.0  188.0  118.0
70         71           Jaylen Warren   RB        28  PIT  27.832991     9     7     194.2   16.8     10.0       10.7      69.0   -2.0   72.0    1.0
71         72           Harold Fannin   TE         6  CLE  22.116359    11     5     152.0   16.2      9.4       10.5      72.0    0.0   77.0    5.0
72         73              Joe Burrow   QB         5  CIN  29.724846     6     4     379.0   14.8      7.1        8.6      53.0  -20.0   49.0  -24.0
73         74         Marvin Harrison   WR        32  ARI  24.057495    14    12     161.4   14.7      8.1       10.0      73.0   -1.0   71.0   -3.0
74         75             Jalen Hurts   QB         6  PHI  28.068446    10     4     378.3   14.1      6.7        8.6      63.0  -12.0   62.0  -13.0
75         76          Brandon Aubrey    K         1  DAL  31.468857    14     1     116.0   13.0     13.0       18.0     131.0   55.0  206.0  130.0
76         77              DK Metcalf   WR        33  PIT  28.714579     9    12     159.0   12.3      7.7       11.2      78.0    1.0   79.0    2.0
77         78     Philadelphia Eagles  DST         4  PHI        NaN    10     2      98.0   12.0     12.0       18.0     138.0   60.0  194.0  116.0
78         79            Tucker Kraft   TE         7   GB  25.826146    11     5     147.6   11.8      5.9        9.1      67.0  -12.0   68.0  -11.0
79         80            Tony Pollard   RB        29  TEN  29.338809     9     7     188.6   11.2      6.8       10.9      81.0    1.0   75.0   -5.0
80         81             Brock Purdy   QB         7   SF  26.680356     8     4     375.3   11.1      4.7        7.5     117.0   36.0   94.0   13.0
81         82        Ka'imi Fairbairn    K         2  HOU  32.588638     8     1     113.0   10.0     10.0       18.0     141.0   59.0  212.0  130.0
82         83          Denver Broncos  DST         5  DEN        NaN    10     2      96.0   10.0     10.0       18.0     136.0   53.0  184.0  101.0
83         84             Alec Pierce   WR        34  IND  26.332649    13    12     156.6    9.9      5.8       10.5      92.0    8.0   91.0    7.0
84         85          Caleb Williams   QB         8  CHI  24.785763    10     4     374.0    9.8      5.2        9.5      76.0   -9.0   66.0  -19.0
85         86              Kyle Pitts   TE         8  ATL  25.902806    11     5     145.2    9.4      4.7        9.1      71.0  -15.0   82.0   -4.0
86         87            Dak Prescott   QB         9  DAL  33.092402    14     4     373.5    9.3      4.9        9.5      89.0    2.0   80.0   -7.0
87         88        Baltimore Ravens  DST         6  BAL        NaN    13     2      95.0    9.0      9.0       18.0     147.0   59.0  205.0  117.0
88         89            J.K. Dobbins   RB        30  DEN  27.707050    10     7     186.4    9.0      5.4       10.7      87.0   -2.0   85.0   -4.0
89         90              Cam Little    K         3  JAX  23.041752     7     1     112.0    9.0      9.0       18.0     144.0   54.0  217.0  127.0
90         91           George Kittle   TE         9   SF  32.895277     8     5     144.5    8.7      4.9       10.2      90.0   -1.0   97.0    6.0
91         92                DJ Moore   WR        35  BUF  39.446954     7    12     155.3    8.6      5.4       11.4      56.0  -36.0   58.0  -34.0
92         93            Jordan Mason   RB        31  MIN  27.274470     6     7     185.6    8.2      4.9       10.7     104.0   11.0  107.0   14.0
93         94         Trevor Lawrence   QB        10  JAX  26.904860     7     4     372.4    8.2      3.4        7.5      97.0    3.0   76.0  -18.0
94         95             Jason Myers    K         4  SEA  35.307324    11     1     111.0    8.0      8.0       18.0     137.0   42.0  218.0  123.0
95         96            Travis Kelce   TE        10   KC  36.906229     5     5     143.4    7.6      4.3       10.2      98.0    2.0  104.0    8.0
96         97       Minnesota Vikings  DST         7  MIN        NaN     6     2      92.0    6.0      6.0       18.0     159.0   62.0  204.0  107.0
97         98           Detroit Lions  DST         8  DET        NaN     6     2      92.0    6.0      6.0       18.0     174.0   76.0  234.0  136.0
98         99    New England Patriots  DST         9   NE        NaN    11     2      92.0    6.0      6.0       18.0     153.0   54.0  199.0  100.0
99        100           Will Reichard    K         5  MIN  25.642710     6     1     109.0    6.0      6.0       18.0     183.0   83.0  284.0  184.0
100       101           Kyle Monangai   RB        32  CHI  24.238193    10     7     183.0    5.6      3.4       10.9      86.0  -15.0  102.0    1.0
101       102            Carnell Tate   WR        36  TEN  21.615332     9    12     151.8    5.1      3.4       11.9      66.0  -36.0   70.0  -32.0
102       103    Jacksonville Jaguars  DST        10  JAX        NaN     7     2      91.0    5.0      5.0       18.0     160.0   57.0  196.0   93.0
103       104        Courtland Sutton   WR        37  DEN  30.893908    10    12     150.7    4.0      2.3       10.4      84.0  -20.0   84.0  -20.0
104       105           Chris Boswell    K         6  PIT  35.463381     9     1     107.0    4.0      4.0       18.0     186.0   81.0  254.0  149.0
105       106             Jaxson Dart   QB        11  NYG  23.304586     8     4     367.5    3.3      2.0       10.7      95.0  -11.0   95.0  -11.0
106       107            Mark Andrews   TE        11  BAL  30.986995    13     5     139.1    3.3      1.9       10.6     120.0   13.0  121.0   14.0
107       108          Evan McPherson    K         7  CIN  27.115674     6     1     106.0    3.0      3.0       18.0     180.0   72.0  241.0  133.0
108       109              Tyler Loop    K         8  BAL  25.075975    13     1     106.0    3.0      3.0       18.0     188.0   79.0  222.0  113.0
109       110          Harrison Mevis    K         9  LAR  24.432580    11     1     106.0    3.0      3.0       18.0     155.0   45.0  230.0  120.0
110       111          Cameron Dicker    K        10  LAC  26.321697     7     1     106.0    3.0      3.0       18.0     135.0   24.0  214.0  103.0
111       112          Matthew Golden   WR        38   GB  23.085558    11    12     149.5    2.8      1.8       11.9     123.0   11.0  130.0   18.0
112       113             Rico Dowdle   RB        33  PIT  28.216290     9     7     179.8    2.4      1.5       10.9      83.0  -30.0   81.0  -32.0
113       114          Jordan Addison   WR        39  MIN  24.594114     6    12     148.8    2.1      1.2       10.0     101.0  -13.0  103.0  -11.0
114       115        Chase McLaughlin    K        11   TB  30.395619    10     1     105.0    2.0      2.0       18.0     205.0   90.0  236.0  121.0
115       116              Jake Bates    K        12  DET  27.498973     6     1     105.0    2.0      2.0       18.0     154.0   38.0  228.0  112.0
116       117     Pittsburgh Steelers  DST        11  PIT        NaN     9     2      88.0    2.0      2.0       18.0     169.0   52.0  201.0   84.0
117       118          Dalton Kincaid   TE        12  BUF  26.872005     7     5     137.2    1.4      0.8       10.0      94.0  -24.0  114.0   -4.0
118       119      Kansas City Chiefs  DST        12   KC        NaN     5     2      87.0    1.0      1.0       18.0     219.0  100.0  213.0   94.0
119       120          Justin Herbert   QB        12  LAC  28.479124     7     4     364.4    0.2      0.1        8.6      80.0  -40.0   69.0  -51.0
120       121         Brenton Strange   TE        13  JAX  25.678303     7     5     135.8    0.0      0.0        9.1     156.0   35.0  145.0   24.0
121       122              Tyler Bass    K        13  BUF  29.544148     7     1     103.0    0.0      0.0       18.0     529.0  407.0  363.0  241.0
122       123       Green Bay Packers  DST        13   GB        NaN    11     2      86.0    0.0      0.0       18.0     206.0   83.0  223.0  100.0
123       124          Dallas Cowboys  DST        14  DAL        NaN    14     2      86.0    0.0      0.0       18.0     238.0  114.0  331.0  207.0
124       125    Los Angeles Chargers  DST        15  LAC        NaN     7     2      86.0    0.0      0.0       18.0     184.0   59.0  203.0   78.0
125       126                  Bo Nix   QB        13  DEN  26.516085    10     4     364.2    0.0      0.0        7.5     118.0   -8.0  100.0  -26.0
126       127            Chris Godwin   WR        40   TB  30.510609    10    12     146.7    0.0      0.0       10.4      96.0  -31.0   83.0  -44.0
127       128           Chuba Hubbard   RB        34  CAR  27.225188     5     7     177.4    0.0      0.0       10.7      74.0  -54.0   90.0  -38.0
128       129         New York Giants  DST        16  NYG        NaN     8     2      86.0    0.0      0.0       18.0     592.0  463.0  366.0  237.0
129       130           Chicago Bears  DST        17  CHI        NaN    10     2      85.0   -1.0     -1.0       18.0     239.0  109.0  321.0  191.0
130       131              Josh Downs   WR        41  IND  25.054073    13    12     145.0   -1.7     -0.9       10.0     110.0  -21.0   96.0  -35.0
131       132             Makai Lemon   WR        42  PHI  22.247775    10    12     145.0   -1.7     -1.1       11.9      85.0  -47.0  111.0  -21.0
132       133         Jonathon Brooks   RB        35  CAR  23.115674     5     7     175.5   -1.9     -1.1       10.4      91.0  -42.0   87.0  -46.0

In [14]:
# RUSH_1D estimator tool as a backup
import pandas as pd

NFLVERSE = "https://github.com/nflverse/nflverse-data/releases/download"

def load_first(candidates, label):
    """Try candidate URLs in order; return the first that loads."""
    for url in candidates:
        try:
            df = (pd.read_parquet(url) if url.endswith(".parquet")
                  else pd.read_csv(url, low_memory=False))
            print(f"OK  {label}: {url.split('/')[-1]}  ({len(df):,} rows)")
            return df
        except Exception as e:
            print(f"    no: {url.split('/')[-1]}  ({type(e).__name__})")
    raise RuntimeError(f"could not load {label}")

def season_stats(year):
    return load_first([
        f"{NFLVERSE}/player_stats/stats_player_season_{year}.parquet",
        f"{NFLVERSE}/player_stats/player_stats_{year}.parquet",
        f"{NFLVERSE}/player_stats/player_stats_{year}.csv.gz",
        f"{NFLVERSE}/stats_player/stats_player_week_{year}.parquet",
        f"{NFLVERSE}/stats_player/stats_player_season_{year}.parquet",
    ], f"season stats {year}")

# ---- fit rushing-first-down rates from actuals ----
frames = []
for y in (2022, 2023, 2024, 2025):
    try:
        frames.append(season_stats(y))
    except Exception as e:
        print(f"skip {y}: {e}")
s = pd.concat(frames, ignore_index=True)
pos_col = "position" if "position" in s.columns else "position_group"
key = "player_id" if "player_id" in s.columns else "player_display_name"

# weekly -> player-season totals
season = (s.groupby([key, pos_col, "season"], as_index=False)
            [["rushing_yards", "rushing_first_downs", "carries"]].sum())

# keep player-seasons with real rushing volume (matches who we actually draft)
sub = season[season["carries"] >= 20]

fit = sub.groupby(pos_col)[["rushing_yards", "rushing_first_downs", "carries"]].sum()
fit["fd_per_yard"] = fit["rushing_first_downs"] / fit["rushing_yards"]
fit["fd_per_att"] = fit["rushing_first_downs"] / fit["carries"]
fit["player_seasons"] = sub.groupby(pos_col).size()
print(fit[["fd_per_yard", "fd_per_att", "player_seasons"]].round(4))

    no: stats_player_season_2022.parquet  (HTTPError)
OK  season stats 2022: player_stats_2022.parquet  (5,631 rows)
    no: stats_player_season_2023.parquet  (HTTPError)
OK  season stats 2023: player_stats_2023.parquet  (5,653 rows)
    no: stats_player_season_2024.parquet  (HTTPError)
OK  season stats 2024: player_stats_2024.parquet  (5,597 rows)
    no: stats_player_season_2025.parquet  (HTTPError)
    no: player_stats_2025.parquet  (HTTPError)
    no: player_stats_2025.csv.gz  (HTTPError)
OK  season stats 2025: stats_player_week_2025.parquet  (19,422 rows)
          fd_per_yard  fd_per_att  player_seasons
position
QB             0.0784      0.3647             155
RB             0.0519      0.2251             381
TE             0.0757      0.3488               3
WR             0.0429      0.2209               7

In [15]:
# ============================================================
# CELL 10 — explain(): why is this player ranked here?
# Decomposes a player's projected points into scoring categories and
# shows the context the scoring can't see (age, experience, injury,
# team change, workload). Reads from `board` if Cell 8 has run, so the
# ADP and FantasyPros ECR columns are available; otherwise from `proj`.
# ============================================================
def explain(name):
    src = board if "board" in globals() else proj
    m = src[src["Player"].str.contains(name, case=False, na=False)]
    if m.empty:
        print(f"no match for '{name}'")
        return
    r = m.iloc[0]

    def g(col):
        v = r.get(col, 0.0)
        try:
            v = float(v)
        except (TypeError, ValueError):
            return 0.0
        return 0.0 if pd.isna(v) else v

    def v(col):
        x = r.get(col) if col in r.index else None
        if x is None:
            return None
        if isinstance(x, float) and pd.isna(x):
            return None
        return x

    # ---------- headline ----------
    adp_txt = (f"ADP {v('ADP_RANK'):.0f}" if v("ADP_RANK") is not None
               else (f"ADP {g('ADP_HALF'):.1f}" if g("ADP_HALF") else "no ADP"))
    print(f"{r['Player']}  ({r['POS']}{r['POS_RANK']}, {r['Team']})")
    print(f"  {r['PROJ_PTS']:.1f} pts | VOR {r['VOR']:.1f} | overall #{r['VOR_RANK']} "
          f"| tier {r['TIER']} | {adp_txt}"
          + (f" | FP ECR {v('ECR'):.0f}" if v("ECR") is not None else ""))

    # ---------- context the scoring cannot see ----------
    bits = []
    if v("AGE") is not None:
        bits.append(f"age {float(v('AGE')):.1f}")
    if v("YEARS_EXP") is not None:
        e = int(float(v("YEARS_EXP")))
        bits.append("ROOKIE" if e == 0 else f"{e}y exp")
    if v("INJURY_BODY_PART"):
        bits.append(f"injury: {v('INJURY_STATUS') or 'listed'} ({v('INJURY_BODY_PART')})")
    elif v("INJURY_STATUS"):
        bits.append(f"injury: {v('INJURY_STATUS')}")
    if v("TEAM_CHANGED_AT"):
        bits.append(f"changed team {str(v('TEAM_CHANGED_AT'))[:10]}")
    bits.append(f"{g('GP'):.0f} games projected")
    if r["POS"] in ("RB", "WR", "TE"):
        bits.append(f"{g('RUSH_ATT') + g('REC'):.0f} touches")
    print("  " + " | ".join(bits))

    if v("INJURY_NOTES"):
        print(f"  note: {str(v('INJURY_NOTES'))[:160]}")

    # ---------- K / DST use Sleeper's own scoring ----------
    if r["POS"] in ("K", "DST"):
        print(f"  replacement {r['POS']}{repl_rank[r['POS']]}: "
              f"{repl_pts[r['POS']]:.1f} pts")
        print("  (scored with Sleeper's own points — the payload omits the "
              "components needed for your league's K/DST rules)")
        return

    # ---------- how much of this is YOUR league's scoring ----------
    sl = g("SLEEPER_PTS_HALF")
    if sl > 0:
        print(f"  league premium: {r['PROJ_PTS'] - sl:+.1f} pts vs standard "
              f"half-PPR ({sl:.1f}) — this is your edge over the draft room")

    # ---------- availability heuristics (Sleeper assumes everyone plays) ----------
    age = float(v("AGE")) if v("AGE") is not None else None
    if r["POS"] == "RB" and age is not None and age >= 28:
        print("  [!] RB age 28+ with no injury discount in the projection — "
              "haircut availability yourself")
    if r["POS"] in ("RB", "WR") and g("RUSH_ATT") + g("REC") >= 300:
        print("  [!] very high projected workload — upside, but concentrated risk")
    if v("TEAM_CHANGED_AT"):
        print("  [!] changed teams — projections lag on new situations, "
              "worth a manual look")

    # ---------- scoring breakdown (sums to PROJ_PTS) ----------
    parts = {
        "pass yds":   g("PASS_YD") * SCORING["pass_yd"],
        "pass TDs":   g("PASS_TD") * SCORING["pass_td"],
        "INTs":       g("INT") * SCORING["int"],
        "rush yds":   g("RUSH_YD") * SCORING["rush_yd"],
        "rush TDs":   g("RUSH_TD") * SCORING["rush_td"],
        "rush 1Ds":   (g("RUSH_FD") if RUSH_FD_OK
                       else g("RUSH_YD") * RUSH_1D_RATES.get(r["POS"], 0.0))
                      * SCORING["rush_fd"],
        "receptions": g("REC") * SCORING["rec"],
        "rec yds":    g("REC_YD") * SCORING["rec_yd"],
        "rec TDs":    g("REC_TD") * SCORING["rec_td"],
        "40+ recs":   g("REC_40P") * SCORING["rec_40p"],
        "2-pt conv":  (g("PASS_2PT") + g("RUSH_2PT") + g("REC_2PT")) * SCORING["two_pt"],
        "fumbles":    g("FL") * SCORING["fumble"],
    }
    print(f"  replacement {r['POS']}{repl_rank[r['POS']]}: {repl_pts[r['POS']]:.1f} pts")
    for k, val in sorted(parts.items(), key=lambda kv: -abs(kv[1])):
        if abs(val) > 0.05:
            print(f"     {k:<12} {val:7.1f}   ({val / r['PROJ_PTS']:5.1%})")


explain("Henry")

Derrick Henry  (RB6, BAL)
  310.4 pts | VOR 133.0 | overall #6 | tier 3 | ADP 18 | FP ECR 22
  age 32.7 | 10y exp | 18 games projected | 298 touches
  league premium: +72.0 pts vs standard half-PPR (238.4) — this is your edge over the draft room
  [!] RB age 28+ with no injury discount in the projection — haircut availability yourself
  replacement RB34: 177.4 pts
     rush yds       140.6   (45.3%)
     rush TDs        72.0   (23.2%)
     rush 1Ds        70.3   (22.6%)
     rec yds         13.3   ( 4.3%)
     receptions       8.5   ( 2.7%)
     rec TDs          6.0   ( 1.9%)
     fumbles         -4.0   (-1.3%)
     2-pt conv        2.0   ( 0.6%)
     40+ recs         1.7   ( 0.5%)

In [16]:
# biggest market discounts in this league's scoring (your sleepers)
sheet[sheet["ADP_RANK"].notna()].sort_values("VALUE", ascending=False).head(80)

     VOR_RANK                 Player  POS  POS_RANK Team        AGE   Bye  TIER  PROJ_PTS    VOR  VOR_ADJ  EXP_GAMES  ADP_RANK  VALUE    ECR  ROOM+
253       254         Andrei Iosivas   WR        84  CIN  26.880219     6    15      79.0  -67.7    -39.6       10.5     790.0  536.0  317.0   63.0
268       269            Evan Engram   TE        42  DEN  31.997262    10     9      58.3  -77.5    -45.6       10.6     788.0  519.0  244.0  -25.0
255       256          Michael Mayer   TE        35   LV  25.155373    13     9      67.2  -68.6    -34.5        9.1     774.0  518.0  326.0   70.0
285       286            Marvin Mims   WR        99  DEN  24.454483    10    16      60.9  -85.8    -47.4       10.0     789.0  503.0  283.0   -3.0
141       142        Atlanta Falcons  DST        21  ATL        NaN    11     2      83.0   -3.0     -3.0       18.0     637.0  495.0  290.0  148.0
135       136     Indianapolis Colts  DST        19  IND        NaN    13     2      84.0   -2.0     -2.0       18.0     631.0  495.0  313.0  177.0
269       270        KaVontae Turpin   WR        91  DAL  30.080767    14    16      66.9  -79.8    -46.3       10.4     765.0  495.0  370.0  100.0
286       287        DeMario Douglas   WR       100   NE  25.730322    11    16      60.6  -86.1    -47.6       10.0     777.0  490.0  327.0   40.0
170       171          Jason Sanders    K        24  NYJ  30.792608    13     1      91.0  -12.0    -12.0       18.0     659.0  488.0  574.0  403.0
304       305        Tyquan Thornton   WR       108   KC  26.067077     5    16      54.6  -92.1    -53.9       10.5     783.0  478.0  269.0  -36.0
292       293              Max Klare   TE        48  LAR  23.151266    11    10      47.3  -88.5    -51.5       10.5     767.0  474.0  350.0   57.0
256       257              Cole Kmet   TE        36  CHI  27.479808    10     9      66.1  -69.7    -38.6       10.0     731.0  474.0  341.0   84.0
317       318          Elic Ayomanor   WR       116  TEN  23.247091     9    16      48.7  -98.0    -64.6       11.9     786.0  468.0  249.0  -69.0
128       129        New York Giants  DST        16  NYG        NaN     8     2      86.0    0.0      0.0       18.0     592.0  463.0  366.0  237.0
315       316          Zavion Thomas   WR       115  CHI  22.546201    10    16      49.2  -97.5    -64.3       11.9     778.0  462.0  386.0   70.0
319       320          Calvin Austin   WR       117  NYG  27.441478     8    16      47.3  -99.4    -58.1       10.5     781.0  461.0  336.0   16.0
230       231           Mason Taylor   TE        32  NYJ  22.316222    13     8      80.4  -55.4    -32.2       10.5     692.0  461.0  276.0   45.0
244       245     Darnell Washington   TE        33  PIT  25.040383     9     9      71.9  -63.9    -32.1        9.1     706.0  461.0  320.0   75.0
142       143               Wil Lutz    K        17  DEN  32.153320    10     1     100.0   -3.0     -3.0       18.0     603.0  460.0  262.0  119.0
284       285           Jahan Dotson   WR        98  ATL  26.444901    11    16      61.6  -85.1    -49.8       10.5     744.0  459.0  324.0   39.0
303       304            Skyler Bell   WR       107  BUF  24.158795     7    16      55.0  -91.7    -50.7       10.0     758.0  454.0  312.0    8.0
222       223           Mike Gesicki   TE        29  CIN  30.913073     6     8      88.1  -47.7    -28.1       10.6     674.0  451.0  306.0   83.0
180       181              Joey Slye    K        27  TEN  30.392882     9     2      84.0  -19.0    -19.0       18.0     632.0  451.0  441.0  260.0
297       298         Xavier Legette   WR       105  CAR  25.587953     5    16      56.9  -89.8    -49.7       10.0     745.0  447.0  278.0  -20.0
287       288              Noah Gray   TE        44   KC  27.340178     5    10      49.5  -86.3    -47.8       10.0     730.0  442.0  344.0   56.0
290       291            Justin Joly   TE        46  DEN  22.146475    10    10      48.8  -87.0    -50.6       10.5     733.0  442.0  356.0   65.0
151       152      Carolina Panthers  DST        22  CAR        NaN     5     2      81.0   -5.0     -5.0       18.0     591.0  439.0  353.0  201.0
221       222            Jaylin Noel   WR        66  HOU  23.991786     8    15      99.6  -47.1    -31.0       11.9     660.0  438.0  186.0  -36.0
272       273              Jack Bech   WR        94   LV  23.704312    13    16      66.4  -80.3    -52.9       11.9     710.0  437.0  242.0  -31.0
342       343          James McCourt    K        58   FA  28.810404   NaN    11       0.0 -103.0   -103.0       18.0     776.0  433.0    NaN    NaN
264       265         Darius Slayton   WR        90  NYG  29.634497     8    15      72.8  -73.9    -46.1       11.2     693.0  428.0  270.0    5.0
229       230          Devaughn Vele   WR        69   NO  28.720055     8    15      94.3  -52.4    -32.7       11.2     655.0  425.0  258.0   28.0
324       325          Luke Musgrave   TE        52   GB  25.995893    11    11      33.8 -102.0    -51.3        9.1     746.0  421.0  394.0   69.0
185       186      Arizona Cardinals  DST        29  ARI        NaN    14     3      66.0  -20.0    -20.0       18.0     606.0  420.0  462.0  276.0
161       162     New Orleans Saints  DST        25   NO        NaN     8     2      77.0   -9.0     -9.0       18.0     582.0  420.0  297.0  135.0
194       195         Miami Dolphins  DST        32  MIA        NaN     6     3      62.0  -24.0    -24.0       18.0     614.0  419.0  409.0  214.0
166       167  Washington Commanders  DST        26  WAS        NaN     7     2      75.0  -11.0    -11.0       18.0     580.0  413.0  428.0  261.0
259       260           Chimere Dike   WR        87  TEN  24.714579     9    15      75.7  -71.0    -39.3       10.0     670.0  410.0  253.0   -7.0
158       159              Nick Folk    K        20  ATL  41.820671    11     1      95.0   -8.0     -8.0       18.0     569.0  410.0  427.0  268.0
152       153   Tampa Bay Buccaneers  DST        23   TB        NaN    10     2      81.0   -5.0     -5.0       18.0     562.0  409.0  380.0  227.0
121       122             Tyler Bass    K        13  BUF  29.544148     7     1     103.0    0.0      0.0       18.0     529.0  407.0  363.0  241.0
172       173            Chad Ryland    K        26  ARI  26.880219    14     1      89.0  -14.0    -14.0       18.0     571.0  398.0  495.0  322.0
327       328       Daniel Bellinger   TE        53  TEN  25.941136     9    11      33.3 -102.5    -51.6        9.1     722.0  394.0  395.0   67.0
361       362             Dan Bailey    K        77   FA  38.598220   NaN    11       0.0 -103.0   -103.0       18.0     747.0  385.0    NaN    NaN
156       157     Cincinnati Bengals  DST        24  CIN        NaN     6     2      79.0   -7.0     -7.0       18.0     541.0  384.0  374.0  217.0
293       294         Marquise Brown   WR       102  PHI  29.242984   NaN    16      57.5  -89.2    -55.7       11.2     672.0  378.0    NaN    NaN
362       363           Chris Naggar    K        78   FA  28.728268   NaN    11       0.0 -103.0   -103.0       18.0     735.0  372.0    NaN    NaN
167       168        Ryan Fitzgerald    K        22  CAR  26.050650     5     1      92.0  -11.0    -11.0       18.0     531.0  363.0  502.0  334.0
200       201               Matt Gay    K        29   LV  32.465435   NaN     3      75.0  -28.0    -28.0       18.0     563.0  362.0    NaN    NaN
366       367           Andrew Mevis    K        82   FA        NaN   NaN    11       0.0 -103.0   -103.0       18.0     728.0  361.0    NaN    NaN
171       172           Jake Elliott    K        25  PHI  31.611225    10     1      90.0  -13.0    -13.0       18.0     526.0  354.0  354.0  182.0
134       135          Buffalo Bills  DST        18  BUF        NaN     7     2      84.0   -2.0     -2.0       18.0     486.0  351.0  229.0   94.0
265       266          Elijah Arroyo   TE        40  SEA  23.408624    11     9      60.6  -75.2    -43.8       10.5     616.0  350.0  333.0   67.0
278       279        Kendrick Bourne   WR        95  ARI  31.077344    14    16      65.0  -81.7    -47.4       10.4     629.0  350.0  362.0   83.0
147       148            Blake Grupe    K        18  IND  27.822040    13     1      99.0   -4.0     -4.0       18.0     497.0  349.0  430.0  282.0
168       169       Cleveland Browns  DST        27  CLE        NaN    11     2      74.0  -12.0    -12.0       18.0     508.0  339.0  252.0   83.0
258       259            Dawson Knox   TE        37  BUF  29.796030     7     9      65.2  -70.6    -42.9       10.9     594.0  335.0  347.0   88.0
163       164          Charlie Smyth    K        21   NO  25.182752     8     1      93.0  -10.0    -10.0       18.0     496.0  332.0  311.0  147.0
311       312           Mack Hollins   WR       113   NE  32.958248    11    16      51.8  -94.9    -60.0       11.4     643.0  331.0  298.0  -14.0
187       188      Las Vegas Raiders  DST        30   LV        NaN    13     3      65.0  -21.0    -21.0       18.0     511.0  323.0  429.0  241.0
302       303            Isaiah Bond   WR       106  CLE  22.464066    11    16      55.0  -91.7    -60.4       11.9     625.0  322.0  308.0    5.0
189       190          New York Jets  DST        31  NYJ        NaN    13     3      64.0  -22.0    -22.0       18.0     509.0  319.0  458.0  268.0
169       170             Jake Moody    K        23   FA  26.773443  None     1      91.0  -12.0    -12.0       18.0     488.0  318.0  426.0  256.0
448       449         Christian Kirk   WR       121   SF  29.785079     8    16      39.2 -107.5    -67.1       11.2     764.0  315.0  273.0 -176.0
457       458           Isaiah Davis   RB        59  NYJ  24.525667    13    15      68.4 -109.0    -66.2       10.9     771.0  313.0  246.0 -212.0
181       182       Tennessee Titans  DST        28  TEN        NaN     9     3      67.0  -19.0    -19.0       18.0     489.0  307.0  400.0  218.0
305       306           Barion Brown   WR       109   NO  22.721424     8    16      54.2  -92.5    -61.0       11.9     611.0  305.0  500.0  194.0
449       450          Michael Trigg   TE        59  DAL  24.180698    14    11      28.2 -107.6    -54.1        9.1     754.0  304.0  504.0   54.0
382       383           Quinn Nordin    K        98   FA  28.043806   NaN    11       0.0 -103.0   -103.0       18.0     682.0  299.0    NaN    NaN
318       319          Samaje Perine   RB        51  CIN  30.959617     6    15      78.0  -99.4    -64.9       11.8     605.0  286.0  260.0  -59.0
281       282      Olamide Zaccheaus   WR        97  ATL  29.108830    11    16      64.4  -82.3    -51.4       11.2     568.0  286.0  348.0   66.0
308       309           Josh Cameron   WR       111  JAX  23.457906     7    16      52.3  -94.4    -62.2       11.9     587.0  278.0  573.0  264.0
438       439             Oscar Delp   TE        54   NO  23.077344     8    11      32.6 -103.2    -60.1       10.5     714.0  275.0  225.0 -214.0
445       446              Zach Ertz   TE        58   FA  35.808350  None    11      30.3 -105.5    -59.8       10.2     720.0  274.0  438.0   -8.0
250       251        Riley Patterson    K        36  MIA  26.984257     6     7      37.0  -66.0    -66.0       18.0     512.0  261.0  641.0  390.0
203       204          Darren Waller   TE        26  CAR  33.965777     5     7     103.8  -32.0    -18.1       10.2     461.0  257.0  322.0  118.0
206       207             Trey Smack    K        30   GB  23.140315    11     4      70.0  -33.0    -33.0       18.0     455.0  248.0  405.0  198.0
514       515          LeQuint Allen   RB        72  JAX  22.072553     7    15      55.8 -121.6    -69.9       10.4     755.0  240.0  261.0 -254.0
226       227         Daniel Carlson    K        33   FA  31.605749    13     5      52.0  -51.0    -51.0       18.0     462.0  235.0  446.0  219.0
505       506          Kyle Williams   WR       138   NE  43.227926    11    16      27.4 -119.3    -75.4       11.4     734.0  228.0  304.0 -202.0

In [17]:
# ============================================================
# FINAL CELL — PRINTABLE DRAFT SHEET (paper workflow)
# Tier breaks are drawn as separator lines so they survive printing.
# ROOM+ = ECR - VOR_RANK: how much later the room (drafting off
#   Yahoo/ECR-style ranks) will take him than your board says.
# ADJ   = VOR discounted for expected games played. If ADJ is well
#   below VOR, that value depends on him staying healthy.
# ============================================================
sheet = board[board["ADP_RANK"].notna() | board["ECR"].notna()].copy()

DEPTH = {"QB": 20, "RB": 45, "WR": 45, "TE": 18, "K": 14, "DST": 14}
HDR = ("rank  player                 tm age bye    proj    vor    adj   ecr room+")

def _fmt(r, with_pos=False):
    age = f"{r['AGE']:.0f}" if pd.notna(r["AGE"]) else "--"
    bye = f"{int(r['Bye'])}" if pd.notna(r["Bye"]) else "--"
    ecr = f"{r['ECR']:.0f}" if pd.notna(r["ECR"]) else "--"
    rp = f"{r['ROOM+']:+.0f}" if pd.notna(r["ROOM+"]) else "--"
    adj = f"{r['VOR_ADJ']:.1f}" if pd.notna(r.get("VOR_ADJ")) else "--"
    who = (f"{r['Player']:<22.22} {r['POS']}{int(r['POS_RANK']):<3}{r['Team']:<4}"
           if with_pos else f"{r['Player']:<22.22} {r['Team']:<4}")
    return (f"{int(r['VOR_RANK']):>4}  {who}{age:>3} {bye:>3}  "
            f"{r['PROJ_PTS']:>6.1f} {r['VOR']:>6.1f} {adj:>6}  {ecr:>4} {rp:>5}")

print(f"FREE STEAK DINNER 2026 — generated {stamp}")
print("VOR is the ranking. ADJ = VOR discounted for expected games played.")
print("ROOM+ positive = the room takes him later than he's worth; you can wait.")

print(f"\n{'#' * 22} OVERALL TOP 60 {'#' * 22}")
print("rank  player                 pos tm  age bye    proj    vor    adj   ecr room+")
for _, r in sheet.sort_values("VOR", ascending=False).head(60).iterrows():
    print(_fmt(r, with_pos=True))

for pos in ["RB", "WR", "QB", "TE", "K", "DST"]:
    p = sheet[sheet["POS"] == pos].sort_values("VOR", ascending=False).head(DEPTH[pos])
    if p.empty:
        continue
    print(f"\n{'=' * 26} {pos} {'=' * 26}")
    print(HDR)
    last_tier = None
    for _, r in p.iterrows():
        if last_tier is not None and r["TIER"] != last_tier:
            print("-" * 72)
        last_tier = r["TIER"]
        print(_fmt(r))

sheet.to_csv(f"printable_cheatsheet_{stamp}.csv", index=False)
print(f"\nsaved printable_cheatsheet_{stamp}.csv")

FREE STEAK DINNER 2026 — generated 2026-08-20
VOR is the ranking. ADJ = VOR discounted for expected games played.
ROOM+ positive = the room takes him later than he's worth; you can wait.

###################### OVERALL TOP 60 ######################
rank  player                 pos tm  age bye    proj    vor    adj   ecr room+
   1  Jahmyr Gibbs           RB1  DET  24   6   368.8  191.4  116.2     1    +0
   2  Bijan Robinson         RB2  ATL  25  11   367.9  190.5  115.6     2    +0
   3  Jonathan Taylor        RB3  IND  28  13   327.2  149.8   89.3     7    +4
   4  Christian McCaffrey    RB4  SF   30   8   312.2  134.8   88.0     8    +4
   5  James Cook             RB5  BUF  27   7   311.9  134.5   80.2    11    +6
   6  Derrick Henry          RB6  BAL  33  13   310.4  133.0   69.7    22   +16
   7  Puka Nacua             WR1  LAR  25  11   272.4  125.7   69.5     4    -3
   8  Ja'Marr Chase          WR2  CIN  27   6   268.3  121.6   71.1     3    -5
   9  Ashton Jeanty          RB7  LV   23  13   297.1  119.7   68.8    12    +3
  10  De'Von Achane          RB8  MIA  25   6   293.8  116.4   70.7    18    +8
  11  Saquon Barkley         RB9  PHI  30  10   292.9  115.5   70.1    16    +5
  12  Kenneth Walker         RB10 KC   26   5   287.1  109.7   66.6    21    +9
  13  Chase Brown            RB11 CIN  26   6   279.6  102.2   60.9    14    +1
  14  Jaxon Smith-Njigba     WR3  SEA  25  11   246.6   99.9   55.2     5    -9
  15  Omarion Hampton        RB12 LAC  23   7   275.0   97.6   56.1    20    +5
  16  Amon-Ra St. Brown      WR4  DET  27   6   238.9   92.2   53.9     6   -10
  17  CeeDee Lamb            WR5  DAL  27  14   232.9   86.2   50.4     9    -8
  18  Nico Collins           WR6  HOU  27   8   229.3   82.6   48.3    19    +1
  19  Josh Allen             QB1  BUF  35   7   442.2   78.0   41.3    27    +8
  20  Brock Bowers           TE1  LV   24  13   213.6   77.8   45.3    17    -3
  21  A.J. Brown             WR7  NE   29  11   215.9   69.2   43.2    15    -6
  22  Breece Hall            RB13 NYJ  25  13   245.5   68.1   41.3    35   +13
  23  Justin Jefferson       WR8  MIN  27   6   214.7   68.0   39.8    10   -13
  24  Drake London           WR9  ATL  25  11   214.5   67.8   37.5    13   -11
  25  George Pickens         WR10 DAL  25  14   214.0   67.3   37.2    23    -2
  26  Kyren Williams         RB14 LAR  26  11   244.3   66.9   39.9    31    +5
  27  Javonte Williams       RB15 DAL  26  14   242.7   65.3   38.9    34    +7
  28  David Montgomery       RB16 HOU  29   8   242.6   65.2   39.6    56   +28
  29  D'Andre Swift          RB17 CHI  28  10   242.1   64.7   38.6    50   +21
  30  Travis Etienne         RB18 NO   28   8   240.8   63.4   37.8    45   +15
  31  Trey McBride           TE2  ARI  27  14   196.5   60.7   33.6    24    -7
  32  Jeremiyah Love         RB19 ARI  21  14   237.8   60.4   34.7    40    +8
  33  Josh Jacobs            RB20 GB   29  11   235.3   57.9   35.1    36    +3
  34  Chris Olave            WR11 NO   26   8   203.4   56.7   33.2    25    -9
  35  Quinshon Judkins       RB21 CLE  23  11   233.8   56.4   32.4    54   +19
  36  Cam Skattebo           RB22 NYG  25   8   229.0   51.6   31.3    51   +15
  37  DeVonta Smith          WR12 PHI  28  10   197.5   50.8   29.7    29    -8
  38  Bucky Irving           RB23 TB   24  10   228.0   50.6   30.7    55   +17
  39  Zay Flowers            WR13 BAL  26  13   197.2   50.5   27.9    30    -9
  40  Ladd McConkey          WR14 LAC  25   7   196.4   49.7   27.5    39    -1
  41  Lamar Jackson          QB2  BAL  30  13   413.4   49.2   23.5    38    -3
  42  Rashee Rice            WR15 KC   26   5   195.6   48.9   28.6    26   -16
  43  Malik Nabers           WR16 NYG  23   8   195.3   48.6   32.0    28   -15
  44  Tee Higgins            WR17 CIN  28   6   194.7   48.0   28.1    33   -11
  45  Emeka Egbuka           WR18 TB   24  10   194.2   47.5   31.3    41    -4
  46  Mike Evans             WR19 SF   33   8   194.2   47.5   30.0    59   +13
  47  Colston Loveland       TE3  CHI  22  10   182.0   46.2   26.9    43    -4
  49  Garrett Wilson         WR21 NYJ  26  13   192.5   45.8   26.8    37   -12
  48  Tetairoa McMillan      WR20 CAR  23   5   192.5   45.8   30.2    32   -16
  50  Jaylen Waddle          WR22 DEN  28  10   191.1   44.4   26.0    42    -8
  51  Parker Washington      WR23 JAX  24   7   186.5   39.8   22.0    67   +16
  52  Terry McLaurin         WR24 WAS  31   7   184.6   37.9   22.0    46    -6
  53  Jameson Williams       WR25 DET  25   6   184.4   37.7   20.8    52    -1
  54  Luther Burden          WR26 CHI  23  10   183.2   36.5   24.1    48    -6
  55  Christian Watson       WR27 GB   27  11   183.1   36.4   21.3    57    +2
  56  Drake Maye             QB3  NE   24  11   399.6   35.4   18.8    44   -12
  57  Rome Odunze            WR28 CHI  24  10   181.0   34.3   19.0    60    +3
  58  Tyler Warren           TE4  IND  24  13   168.9   33.1   16.6    53    -5
  59  Jadarian Price         RB24 SEA  23  11   208.0   30.6   17.6    65    +6
  60  Sam LaPorta            TE5  DET  26   6   166.2   30.4   15.3    78   +18

========================== RB ==========================
rank  player                 tm age bye    proj    vor    adj   ecr room+
   1  Jahmyr Gibbs           DET  24   6   368.8  191.4  116.2     1    +0
   2  Bijan Robinson         ATL  25  11   367.9  190.5  115.6     2    +0
------------------------------------------------------------------------
   3  Jonathan Taylor        IND  28  13   327.2  149.8   89.3     7    +4
------------------------------------------------------------------------
   4  Christian McCaffrey    SF   30   8   312.2  134.8   88.0     8    +4
   5  James Cook             BUF  27   7   311.9  134.5   80.2    11    +6
   6  Derrick Henry          BAL  33  13   310.4  133.0   69.7    22   +16
------------------------------------------------------------------------
   9  Ashton Jeanty          LV   23  13   297.1  119.7   68.8    12    +3
  10  De'Von Achane          MIA  25   6   293.8  116.4   70.7    18    +8
  11  Saquon Barkley         PHI  30  10   292.9  115.5   70.1    16    +5
  12  Kenneth Walker         KC   26   5   287.1  109.7   66.6    21    +9
------------------------------------------------------------------------
  13  Chase Brown            CIN  26   6   279.6  102.2   60.9    14    +1
  15  Omarion Hampton        LAC  23   7   275.0   97.6   56.1    20    +5
------------------------------------------------------------------------
  22  Breece Hall            NYJ  25  13   245.5   68.1   41.3    35   +13
  26  Kyren Williams         LAR  26  11   244.3   66.9   39.9    31    +5
  27  Javonte Williams       DAL  26  14   242.7   65.3   38.9    34    +7
  28  David Montgomery       HOU  29   8   242.6   65.2   39.6    56   +28
  29  D'Andre Swift          CHI  28  10   242.1   64.7   38.6    50   +21
  30  Travis Etienne         NO   28   8   240.8   63.4   37.8    45   +15
  32  Jeremiyah Love         ARI  21  14   237.8   60.4   34.7    40    +8
  33  Josh Jacobs            GB   29  11   235.3   57.9   35.1    36    +3
  35  Quinshon Judkins       CLE  23  11   233.8   56.4   32.4    54   +19
  36  Cam Skattebo           NYG  25   8   229.0   51.6   31.3    51   +15
  38  Bucky Irving           TB   24  10   228.0   50.6   30.7    55   +17
------------------------------------------------------------------------
  59  Jadarian Price         SEA  23  11   208.0   30.6   17.6    65    +6
  63  Bhayshul Tuten         JAX  25   7   201.7   24.3   14.8    63    +0
  67  Rhamondre Stevenson    NE   29  11   196.7   19.3   11.7    73    +6
  69  TreVeyon Henderson     NE   24  11   195.0   17.6   10.1    64    -5
  71  Jaylen Warren          PIT  28   9   194.2   16.8   10.0    72    +1
  80  Tony Pollard           TEN  29   9   188.6   11.2    6.8    75    -5
  89  J.K. Dobbins           DEN  28  10   186.4    9.0    5.4    85    -4
  93  Jordan Mason           MIN  27   6   185.6    8.2    4.9   107   +14
 101  Kyle Monangai          CHI  24  10   183.0    5.6    3.4   102    +1
 113  Rico Dowdle            PIT  28   9   179.8    2.4    1.5    81   -32
 128  Chuba Hubbard          CAR  27   5   177.4    0.0    0.0    90   -38
 133  Jonathon Brooks        CAR  23   5   175.5   -1.9   -1.1    87   -46
------------------------------------------------------------------------
 165  Blake Corum            LAR  26  11   167.2  -10.2   -6.2    92   -73
 174  Chris Rodriguez        JAX  27   7   162.9  -14.5   -8.6   123   -51
------------------------------------------------------------------------
 193  RJ Harvey              DEN  26  10   155.0  -22.4  -13.6    93  -100
 194  Kenny Gainwell         TB   27  10   154.4  -23.0  -13.7   106   -88
 198  Aaron Jones            MIN  32   6   151.7  -25.7  -16.8   115   -83
 199  Jacory Croskey-Merritt WAS  25   7   151.0  -26.4  -16.0   101   -98
------------------------------------------------------------------------
 214  Rachaad White          WAS  28   7   137.9  -39.5  -23.5   113  -101
------------------------------------------------------------------------
 224  Tyrone Tracy           NYG  27   8   129.3  -48.1  -28.7   133   -91
------------------------------------------------------------------------
 235  Tyjae Spears           TEN  25   9   120.0  -57.4  -34.8   138   -97
------------------------------------------------------------------------
 250  Keaton Mitchell        LAC  25   7   111.4  -66.0  -40.1   142  -108

========================== WR ==========================
rank  player                 tm age bye    proj    vor    adj   ecr room+
   7  Puka Nacua             LAR  25  11   272.4  125.7   69.5     4    -3
------------------------------------------------------------------------
   8  Ja'Marr Chase          CIN  27   6   268.3  121.6   71.1     3    -5
------------------------------------------------------------------------
  14  Jaxon Smith-Njigba     SEA  25  11   246.6   99.9   55.2     5    -9
------------------------------------------------------------------------
  16  Amon-Ra St. Brown      DET  27   6   238.9   92.2   53.9     6   -10
------------------------------------------------------------------------
  17  CeeDee Lamb            DAL  27  14   232.9   86.2   50.4     9    -8
  18  Nico Collins           HOU  27   8   229.3   82.6   48.3    19    +1
------------------------------------------------------------------------
  21  A.J. Brown             NE   29  11   215.9   69.2   43.2    15    -6
  23  Justin Jefferson       MIN  27   6   214.7   68.0   39.8    10   -13
  24  Drake London           ATL  25  11   214.5   67.8   37.5    13   -11
  25  George Pickens         DAL  25  14   214.0   67.3   37.2    23    -2
------------------------------------------------------------------------
  34  Chris Olave            NO   26   8   203.4   56.7   33.2    25    -9
------------------------------------------------------------------------
  37  DeVonta Smith          PHI  28  10   197.5   50.8   29.7    29    -8
  39  Zay Flowers            BAL  26  13   197.2   50.5   27.9    30    -9
  40  Ladd McConkey          LAC  25   7   196.4   49.7   27.5    39    -1
  42  Rashee Rice            KC   26   5   195.6   48.9   28.6    26   -16
  43  Malik Nabers           NYG  23   8   195.3   48.6   32.0    28   -15
  44  Tee Higgins            CIN  28   6   194.7   48.0   28.1    33   -11
  46  Mike Evans             SF   33   8   194.2   47.5   30.0    59   +13
  45  Emeka Egbuka           TB   24  10   194.2   47.5   31.3    41    -4
  49  Garrett Wilson         NYJ  26  13   192.5   45.8   26.8    37   -12
  48  Tetairoa McMillan      CAR  23   5   192.5   45.8   30.2    32   -16
  50  Jaylen Waddle          DEN  28  10   191.1   44.4   26.0    42    -8
------------------------------------------------------------------------
  51  Parker Washington      JAX  24   7   186.5   39.8   22.0    67   +16
  52  Terry McLaurin         WAS  31   7   184.6   37.9   22.0    46    -6
  53  Jameson Williams       DET  25   6   184.4   37.7   20.8    52    -1
  54  Luther Burden          CHI  23  10   183.2   36.5   24.1    48    -6
  55  Christian Watson       GB   27  11   183.1   36.4   21.3    57    +2
  57  Rome Odunze            CHI  24  10   181.0   34.3   19.0    60    +3
------------------------------------------------------------------------
  61  Jayden Reed            GB   26  11   173.8   27.1   15.9   109   +48
  62  Brian Thomas           JAX  24   7   171.4   24.7   16.3    74   +12
------------------------------------------------------------------------
  65  Davante Adams          LAR  34  11   167.3   20.6   13.0    47   -18
------------------------------------------------------------------------
  74  Marvin Harrison        ARI  24  14   161.4   14.7    8.1    71    -3
  77  DK Metcalf             PIT  29   9   159.0   12.3    7.7    79    +2
  84  Alec Pierce            IND  26  13   156.6    9.9    5.8    91    +7
  92  DJ Moore               BUF  39   7   155.3    8.6    5.4    58   -34
 102  Carnell Tate           TEN  22   9   151.8    5.1    3.4    70   -32
 104  Courtland Sutton       DEN  31  10   150.7    4.0    2.3    84   -20
 112  Matthew Golden         GB   23  11   149.5    2.8    1.8   130   +18
 114  Jordan Addison         MIN  25   6   148.8    2.1    1.2   103   -11
 127  Chris Godwin           TB   31  10   146.7    0.0    0.0    83   -44
 131  Josh Downs             IND  25  13   145.0   -1.7   -0.9    96   -35
 132  Makai Lemon            PHI  22  10   145.0   -1.7   -1.1   111   -21
 134  Jakobi Meyers          JAX  30   7   144.8   -1.9   -1.2   112   -22
 139  Xavier Worthy          KC   23   5   144.0   -2.7   -1.8   124   -15
 144  Michael Pittman        PIT  29   9   143.6   -3.1   -1.9    86   -58

========================== QB ==========================
rank  player                 tm age bye    proj    vor    adj   ecr room+
  19  Josh Allen             BUF  35   7   442.2   78.0   41.3    27    +8
------------------------------------------------------------------------
  41  Lamar Jackson          BAL  30  13   413.4   49.2   23.5    38    -3
------------------------------------------------------------------------
  56  Drake Maye             NE   24  11   399.6   35.4   18.8    44   -12
------------------------------------------------------------------------
  64  Jayden Daniels         WAS  26   7   385.0   20.8   11.0    61    -3
  73  Joe Burrow             CIN  30   6   379.0   14.8    7.1    49   -24
  75  Jalen Hurts            PHI  28  10   378.3   14.1    6.7    62   -13
  81  Brock Purdy            SF   27   8   375.3   11.1    4.7    94   +13
  85  Caleb Williams         CHI  25  10   374.0    9.8    5.2    66   -19
  87  Dak Prescott           DAL  33  14   373.5    9.3    4.9    80    -7
  94  Trevor Lawrence        JAX  27   7   372.4    8.2    3.4    76   -18
 106  Jaxson Dart            NYG  23   8   367.5    3.3    2.0    95   -11
 120  Justin Herbert         LAC  28   7   364.4    0.2    0.1    69   -51
 126  Bo Nix                 DEN  27  10   364.2    0.0    0.0   100   -26
 163  Patrick Mahomes        KC   31   5   354.8   -9.4   -4.3    98   -65
 180  Jared Goff             DET  32   6   346.1  -18.1   -8.2   110   -70
 184  Matthew Stafford       LAR  39  11   345.2  -19.0  -10.1   108   -76
 189  Jordan Love            GB   28  11   342.6  -21.6   -9.1   122   -67
 191  Baker Mayfield         TB   31  10   342.2  -22.0  -10.0   120   -71
 192  Kyler Murray           MIN  29   6   341.8  -22.4  -10.7   116   -76
 197  Malik Willis           MIA  27   6   339.7  -24.5  -10.3   136   -61

========================== TE ==========================
rank  player                 tm age bye    proj    vor    adj   ecr room+
  20  Brock Bowers           LV   24  13   213.6   77.8   45.3    17    -3
------------------------------------------------------------------------
  31  Trey McBride           ARI  27  14   196.5   60.7   33.6    24    -7
------------------------------------------------------------------------
  47  Colston Loveland       CHI  22  10   182.0   46.2   26.9    43    -4
------------------------------------------------------------------------
  58  Tyler Warren           IND  24  13   168.9   33.1   16.6    53    -5
  60  Sam LaPorta            DET  26   6   166.2   30.4   15.3    78   +18
------------------------------------------------------------------------
  72  Harold Fannin          CLE  22  11   152.0   16.2    9.4    77    +5
  79  Tucker Kraft           GB   26  11   147.6   11.8    5.9    68   -11
  86  Kyle Pitts             ATL  26  11   145.2    9.4    4.7    82    -4
  91  George Kittle          SF   33   8   144.5    8.7    4.9    97    +6
  96  Travis Kelce           KC   37   5   143.4    7.6    4.3   104    +8
 107  Mark Andrews           BAL  31  13   139.1    3.3    1.9   121   +14
 118  Dalton Kincaid         BUF  27   7   137.2    1.4    0.8   114    -4
 121  Brenton Strange        JAX  26   7   135.8    0.0    0.0   145   +24
 145  Isaiah Likely          NYG  26   8   132.5   -3.3   -1.8   118   -27
 150  Jake Ferguson          DAL  28  14   131.8   -4.0   -2.2   119   -31
 155  Hunter Henry           NE   32  11   130.3   -5.5   -3.2   146    -9
 158  T.J. Hockenson         MIN  29   6   128.6   -7.2   -4.4   166    +8
------------------------------------------------------------------------
 176  AJ Barner              SEA  24  11   119.9  -15.9   -8.0   170    -6

========================== K ==========================
rank  player                 tm age bye    proj    vor    adj   ecr room+
  76  Brandon Aubrey         DAL  31  14   116.0   13.0   13.0   206  +130
  82  Ka'imi Fairbairn       HOU  33   8   113.0   10.0   10.0   212  +130
  90  Cam Little             JAX  23   7   112.0    9.0    9.0   217  +127
  95  Jason Myers            SEA  35  11   111.0    8.0    8.0   218  +123
 100  Will Reichard          MIN  26   6   109.0    6.0    6.0   284  +184
 105  Chris Boswell          PIT  35   9   107.0    4.0    4.0   254  +149
 108  Evan McPherson         CIN  27   6   106.0    3.0    3.0   241  +133
 109  Tyler Loop             BAL  25  13   106.0    3.0    3.0   222  +113
 110  Harrison Mevis         LAR  24  11   106.0    3.0    3.0   230  +120
 111  Cameron Dicker         LAC  26   7   106.0    3.0    3.0   214  +103
 115  Chase McLaughlin       TB   30  10   105.0    2.0    2.0   236  +121
 116  Jake Bates             DET  27   6   105.0    2.0    2.0   228  +112
 122  Tyler Bass             BUF  30   7   103.0    0.0    0.0   363  +241
 138  Eddy Pineiro           SF   31   8   101.0   -2.0   -2.0   226   +88

========================== DST ==========================
rank  player                 tm age bye    proj    vor    adj   ecr room+
  66  Los Angeles Rams       LAR  --  11   106.0   20.0   20.0   187  +121
  68  Houston Texans         HOU  --   8   104.0   18.0   18.0   178  +110
  70  Seattle Seahawks       SEA  --  11   103.0   17.0   17.0   188  +118
------------------------------------------------------------------------
  78  Philadelphia Eagles    PHI  --  10    98.0   12.0   12.0   194  +116
  83  Denver Broncos         DEN  --  10    96.0   10.0   10.0   184  +101
  88  Baltimore Ravens       BAL  --  13    95.0    9.0    9.0   205  +117
  97  Minnesota Vikings      MIN  --   6    92.0    6.0    6.0   204  +107
  98  Detroit Lions          DET  --   6    92.0    6.0    6.0   234  +136
  99  New England Patriots   NE   --  11    92.0    6.0    6.0   199  +100
 103  Jacksonville Jaguars   JAX  --   7    91.0    5.0    5.0   196   +93
 117  Pittsburgh Steelers    PIT  --   9    88.0    2.0    2.0   201   +84
 119  Kansas City Chiefs     KC   --   5    87.0    1.0    1.0   213   +94
 123  Green Bay Packers      GB   --  11    86.0    0.0    0.0   223  +100
 124  Dallas Cowboys         DAL  --  14    86.0    0.0    0.0   331  +207

saved printable_cheatsheet_2026-08-20.csv